export const data = [
  {
    bodyList: [
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'U8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 16637,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '087d44781fbc4cf59ded16f788e823f9',
        paramKey: 'work_mode',
        paramName: '工作方式',
        paramType: 'SELECT',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '待机',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '2',
            success: false,
            value: '手动',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '指向',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '4',
            success: false,
            value: '数引',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '5',
            success: false,
            value: '程引',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '6',
            success: false,
            value: '自动跟踪1',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '7',
            success: false,
            value: '自动跟踪2',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '9',
            success: false,
            value: '收藏',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '10',
            success: false,
            value: '归零',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 16642,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '087d44781fbc4cf59ded16f788e823f9',
        paramKey: 'azimuth_angle',
        paramName: '方位角度',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 16643,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '087d44781fbc4cf59ded16f788e823f9',
        paramKey: 'pitch_angle',
        paramName: '俯仰角度',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'ACU',
    deviceId: '260D0101',
    deviceStatus: 'OFF_LINE',
    name: ' 天线控制',
  },
  {
    bodyList: [
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 19772,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '4990d699055b41edadd855566418d29a',
        paramKey: '',
        paramName: '工作模式',
        paramType: 'SELECT',
        patternUuid: '0997beb66e984ed4bf2b4c8bec550f7b',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '标准',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '扩频2',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '4',
            success: false,
            value: 'FM模式',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '5',
            success: false,
            value: '双向数传模式',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19591,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '4d8506d9e0f349ac94259964dcd8302c',
        paramKey: 'bbe_work_mode',
        paramName: '工作模式',
        paramType: 'SELECT',
        patternUuid: '8a994ea301f142c4b509d47f05478941',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '标准',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '扩频2',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '4',
            success: false,
            value: 'FM',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '5',
            success: false,
            value: '四通道',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 19623,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '104594b76bd34c0d8c36d1c8021f4119',
        paramKey: 'bbe_work_mode',
        paramName: '工作模式',
        paramType: 'SELECT',
        patternUuid: '91b11451cf99407eaeb59485264598a4',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '标准',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '扩频2',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '4',
            success: false,
            value: 'FM模式',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '5',
            success: false,
            value: '双向数传模式',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 19818,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e11ec8a3ad394e3e9ad33a022315be81',
        paramKey: '',
        paramName: '载波',
        paramType: 'SELECT',
        patternUuid: '0997beb66e984ed4bf2b4c8bec550f7b',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '锁定',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 19820,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e11ec8a3ad394e3e9ad33a022315be81',
        paramKey: '',
        paramName: '帧同步',
        paramType: 'SELECT',
        patternUuid: '0997beb66e984ed4bf2b4c8bec550f7b',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '锁定',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19654,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'ea3b576f42aa4596b89186010f54e43b',
        paramKey: 'bbe_telemetry_carrier_lock',
        paramName: '遥测载波锁定',
        paramType: 'STATUS',
        patternUuid: '91b11451cf99407eaeb59485264598a4',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19655,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'ea3b576f42aa4596b89186010f54e43b',
        paramKey: 'bbe_telemetry_pseudo_code_lock',
        paramName: '遥测伪码锁定',
        paramType: 'STATUS',
        patternUuid: '91b11451cf99407eaeb59485264598a4',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19761,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '752613ac8fc94e3db3135fe680f5fd3d',
        paramKey: 'bbe_telemetry_carrier_lock',
        paramName: '遥测载波',
        paramType: 'STATUS',
        patternUuid: '8a994ea301f142c4b509d47f05478941',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: true,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19764,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '752613ac8fc94e3db3135fe680f5fd3d',
        paramKey: 'bbe_telemetry_frame_sync_lock',
        paramName: '遥测帧同步',
        paramType: 'STATUS',
        patternUuid: '8a994ea301f142c4b509d47f05478941',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: true,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'BBE',
    deviceId: '26020101',
    deviceStatus: 'OFF_LINE',
    name: '综合基带(测控)',
  },
  {
    bodyList: [
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 16204,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '4b9f24615bc84d079440f526b0ede0b4',
        paramKey: 'bbe_work_mode',
        paramName: '工作模式',
        paramType: 'SELECT',
        patternUuid: '7892703cb4654dc78ff2ddeef21bd3c3',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '标准',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '扩频2',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '4',
            success: false,
            value: 'FM',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '5',
            success: false,
            value: '四通道',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 18061,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'a629ed70490242ce9ec5a8d05839775c',
        paramKey: '',
        paramName: '工作模式',
        paramType: 'SELECT',
        patternUuid: 'eef3973bd1a7495abf4df0064a0a208c',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '标准',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '扩频2',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '4',
            success: false,
            value: 'FM模式',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '5',
            success: false,
            value: '双向数传模式',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 17628,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'bbfbcff3e7104319bf7a5340f9f8a979',
        paramKey: 'bbe_work_mode',
        paramName: '工作模式',
        paramType: 'SELECT',
        patternUuid: 'b8b67389c23544d49a76b709397b34ff',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '标准',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '扩频2',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '4',
            success: false,
            value: 'FM模式',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '5',
            success: false,
            value: '双向数传模式',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17659,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'b69983c6875f40c1ae2228092a06dab9',
        paramKey: 'bbe_telemetry_carrier_lock',
        paramName: '遥测载波锁定',
        paramType: 'STATUS',
        patternUuid: 'b8b67389c23544d49a76b709397b34ff',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: true,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17660,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'b69983c6875f40c1ae2228092a06dab9',
        paramKey: 'bbe_telemetry_pseudo_code_lock',
        paramName: '遥测伪码锁定',
        paramType: 'STATUS',
        patternUuid: 'b8b67389c23544d49a76b709397b34ff',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: true,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 18333,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'cb3e85caadd44f0c944988bbbc6838bc',
        paramKey: '',
        paramName: '载波',
        paramType: 'SELECT',
        patternUuid: 'eef3973bd1a7495abf4df0064a0a208c',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '锁定',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 18335,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'cb3e85caadd44f0c944988bbbc6838bc',
        paramKey: '',
        paramName: '帧同步',
        paramType: 'SELECT',
        patternUuid: 'eef3973bd1a7495abf4df0064a0a208c',
        selectConfig: [
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '锁定',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17766,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '464bf2db83b440ee8373b0a02250c86f',
        paramKey: 'bbe_telemetry_carrier_lock',
        paramName: '遥测载波',
        paramType: 'STATUS',
        patternUuid: '7892703cb4654dc78ff2ddeef21bd3c3',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: true,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17769,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '464bf2db83b440ee8373b0a02250c86f',
        paramKey: 'bbe_telemetry_frame_sync_lock',
        paramName: '遥测帧同步',
        paramType: 'STATUS',
        patternUuid: '7892703cb4654dc78ff2ddeef21bd3c3',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: true,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'BBE2',
    deviceId: '26020102',
    deviceStatus: 'OFF_LINE',
    name: '综合基带(中低速)',
  },
  {
    bodyList: [
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19236,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'c4bb0a76781a4a58a80563c743c3f179',
        paramKey: 'ddt_jietiao_carrier_lock',
        paramName: '载波',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '正在锁定',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '失锁',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '2',
            success: true,
            value: '锁定',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19237,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'c4bb0a76781a4a58a80563c743c3f179',
        paramKey: 'ddt_jietiao_ebno',
        paramName: 'Eb/No',
        paramType: 'FLOAT',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19254,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'd974096c00e246b2ba2619df38ea7346',
        paramKey: 'ddt_jietiao_vsync_lock',
        paramName: '帧同步',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '搜索',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '确认',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '2',
            success: true,
            value: '锁定',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '保护',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19257,
        ifSet: 0,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'd974096c00e246b2ba2619df38ea7346',
        paramKey: 'ddt_jietiao_rsldpc_lock',
        paramName: '译码',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '搜索',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '确认',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '2',
            success: true,
            value: '锁定',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3',
            success: false,
            value: '保护',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'DDT',
    deviceId: '26120101',
    deviceStatus: 'OFF_LINE',
    name: '高速数传基带',
  },
  {
    bodyList: [
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I64',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17369,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 0,
        loopCount: 1,
        loopParse: 0,
        originUuid: 'bfd9f94533e74f74a7d6d6e48ac4ae2b',
        paramKey: '',
        paramName: '工作频率',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I16',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17370,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 0,
        loopCount: 1,
        loopParse: 0,
        originUuid: 'bfd9f94533e74f74a7d6d6e48ac4ae2b',
        paramKey: '',
        paramName: '跟踪方式',
        paramType: 'H',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '3634',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3635',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3636',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3637',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3638',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3639',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3670',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3733',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3134',
            success: false,
            value: '1.5MHz跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3135',
            success: false,
            value: '3MHz跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3136',
            success: false,
            value: '6MHz跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3137',
            success: false,
            value: '23MHz跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3333',
            success: false,
            value: '信标跟踪',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17385,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 0,
        loopCount: 1,
        loopParse: 0,
        originUuid: 'bfd9f94533e74f74a7d6d6e48ac4ae2b',
        paramKey: '',
        paramName: '接收机状态',
        paramType: 'H',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: true,
            key: '30',
            success: false,
            value: '故障',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '31',
            success: true,
            value: '正常',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'TRK',
    deviceId: '260F0101',
    deviceStatus: 'OFF_LINE',
    name: '跟踪接收机',
  },
  {
    bodyList: [
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I64',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17369,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 0,
        loopCount: 1,
        loopParse: 0,
        originUuid: 'bfd9f94533e74f74a7d6d6e48ac4ae2b',
        paramKey: '',
        paramName: '工作频率',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I16',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17370,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 0,
        loopCount: 1,
        loopParse: 0,
        originUuid: 'bfd9f94533e74f74a7d6d6e48ac4ae2b',
        paramKey: '',
        paramName: '跟踪方式',
        paramType: 'H',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '3634',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3635',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3636',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3637',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3638',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3639',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3670',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3733',
            success: false,
            value: '扩频跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3134',
            success: false,
            value: '1.5MHz跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3135',
            success: false,
            value: '3MHz跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3136',
            success: false,
            value: '6MHz跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3137',
            success: false,
            value: '23MHz跟踪',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '3333',
            success: false,
            value: '信标跟踪',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17385,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 0,
        loopCount: 1,
        loopParse: 0,
        originUuid: 'bfd9f94533e74f74a7d6d6e48ac4ae2b',
        paramKey: '',
        paramName: '接收机状态',
        paramType: 'H',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: true,
            key: '30',
            success: false,
            value: '故障',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '31',
            success: true,
            value: '正常',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'TRK2',
    deviceId: '260F0102',
    deviceStatus: 'OFF_LINE',
    name: '跟踪接收机',
  },
  {
    bodyList: [],
    device: 'IF_MATRIX',
    deviceId: '26080101',
    deviceStatus: 'OFF_LINE',
    name: '中频矩阵',
  },
  {
    bodyList: [
      {
        bindBodyId: 17515,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'e3a08d11cfc04b26b3af716d8e9c59ff',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17490,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '08ada972f0fe4fa4859318d7f6b893fa',
        paramKey: '',
        paramName: '输入频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHZ',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 17512,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '7055a7cb83324eccb56a4bbc39c90ac6',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17492,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '08ada972f0fe4fa4859318d7f6b893fa',
        paramKey: '',
        paramName: '70M增益',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'XDC1',
    deviceId: '26030106',
    deviceStatus: 'OFF_LINE',
    name: 'X下变频器-遥测',
  },
  {
    bodyList: [
      {
        bindBodyId: 19330,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '7114abe1aa1d413bbe4996f416c5a452',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19305,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '4d8d8fcd1c38405a955318ebbc55a269',
        paramKey: '',
        paramName: '输入频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHZ',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 19328,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c792f7a73c2540ee8289c7d653e1b03f',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19308,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '4d8d8fcd1c38405a955318ebbc55a269',
        paramKey: '',
        paramName: '1.2G增益',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'XDC2',
    deviceId: '26030107',
    deviceStatus: 'OFF_LINE',
    name: 'X下变频器-数传左',
  },
  {
    bodyList: [
      {
        bindBodyId: 19330,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '7114abe1aa1d413bbe4996f416c5a452',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19305,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '4d8d8fcd1c38405a955318ebbc55a269',
        paramKey: '',
        paramName: '输入频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHZ',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 19328,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c792f7a73c2540ee8289c7d653e1b03f',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 19308,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '4d8d8fcd1c38405a955318ebbc55a269',
        paramKey: '',
        paramName: '1.2G增益',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'XDC3',
    deviceId: '26030108',
    deviceStatus: 'OFF_LINE',
    name: 'X下变频器-数传右',
  },
  {
    bodyList: [
      {
        bindBodyId: 16345,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'bce37d225a1643cbb1da2782f3c32680',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 16874,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '2301c555ded44bfe972d0ef4f029927b',
        paramKey: '',
        paramName: '输入频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHZ',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 16967,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '537b722e06ac493283b2b48ff8aa769c',
        byteType: 'I8',
        early: false,
        earlyRange: null,
        id: 16876,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '2301c555ded44bfe972d0ef4f029927b',
        paramKey: '',
        paramName: '通道增益',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 16885,
        ifSet: 0,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '2301c555ded44bfe972d0ef4f029927b',
        paramKey: '',
        paramName: '输出频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'SDC1',
    deviceId: '26030103',
    deviceStatus: 'OFF_LINE',
    name: 'S下变频器-左旋',
  },
  {
    bodyList: [
      {
        bindBodyId: 16345,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'bce37d225a1643cbb1da2782f3c32680',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 16874,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '2301c555ded44bfe972d0ef4f029927b',
        paramKey: '',
        paramName: '输入频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHZ',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 16967,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '537b722e06ac493283b2b48ff8aa769c',
        byteType: 'I8',
        early: false,
        earlyRange: null,
        id: 16876,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '2301c555ded44bfe972d0ef4f029927b',
        paramKey: '',
        paramName: '通道增益',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: null,
        id: 16885,
        ifSet: 0,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '2301c555ded44bfe972d0ef4f029927b',
        paramKey: '',
        paramName: '输出频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'SDC2',
    deviceId: '26030102',
    deviceStatus: 'OFF_LINE',
    name: 'S下变频器-右旋',
  },
  {
    bodyList: [
      {
        bindBodyId: 16932,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I64',
        early: false,
        earlyRange: null,
        id: 17580,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '工作频率',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHz',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 16933,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I16',
        early: false,
        earlyRange: null,
        id: 17582,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '射频衰减',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 16934,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I16',
        early: false,
        earlyRange: null,
        id: 17581,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '中频衰减',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'X_CIN',
    deviceId: '260C0102',
    deviceStatus: 'OFF_LINE',
    name: 'X合成网络',
  },
  {
    bodyList: [
      {
        bindBodyId: 16932,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I64',
        early: false,
        earlyRange: null,
        id: 17580,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '工作频率',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHz',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 16933,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I16',
        early: false,
        earlyRange: null,
        id: 17582,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '射频衰减',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 16934,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I16',
        early: false,
        earlyRange: null,
        id: 17581,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '中频衰减',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'S_CIN',
    deviceId: '260C0101',
    deviceStatus: 'OFF_LINE',
    name: 'S合成网络-左旋',
  },
  {
    bodyList: [
      {
        bindBodyId: 16932,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I64',
        early: false,
        earlyRange: null,
        id: 17580,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '工作频率',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHz',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 16933,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I16',
        early: false,
        earlyRange: null,
        id: 17582,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '射频衰减',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 16934,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c6d34ce7fffc4e88b4cdda2af60d204d',
        byteType: 'I16',
        early: false,
        earlyRange: null,
        id: 17581,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'e13695263c3e4715b44b3788152cf6fd',
        paramKey: '',
        paramName: '中频衰减',
        paramType: 'STR_VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'S_CIN2',
    deviceId: '260C0103',
    deviceStatus: 'OFF_LINE',
    name: 'S合成网络-右旋',
  },
  {
    bodyList: [
      {
        bindBodyId: 17448,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '4a575f4b848d4e218418854dea03ce6e',
        byteType: 'U32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17418,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'a9203f41ef5c48a6990f6412609a6208',
        paramKey: '',
        paramName: '射频频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHz',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 17452,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'ec1d955d79a84aaead168ae35bcab4f4',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17426,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'a9203f41ef5c48a6990f6412609a6208',
        paramKey: 'x_buc_amplifier',
        paramName: '功放开关',
        paramType: 'SELECT',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '关闭',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '开启',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I16_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17434,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'a9203f41ef5c48a6990f6412609a6208',
        paramKey: '',
        paramName: '发射功率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.1,
        valueUnit: 'dBm',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'X_BUC',
    deviceId: '26070102',
    deviceStatus: 'OFF_LINE',
    name: 'X-BUC',
  },
  {
    bodyList: [
      {
        bindBodyId: 17484,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '5116af83c411481cb43a2b60f0e3a2e6',
        byteType: 'U32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17454,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '6d2a4d5d3f6441889ca5889c638ec998',
        paramKey: '',
        paramName: '射频频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.0001,
        valueUnit: 'MHz',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 17488,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'c5e2498a9dd443b292cc264efff552c4',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17462,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '6d2a4d5d3f6441889ca5889c638ec998',
        paramKey: 's_buc_amplifier',
        paramName: '功放开关',
        paramType: 'SELECT',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '0',
            success: false,
            value: '关闭',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '1',
            success: false,
            value: '开启',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I16_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 17470,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '6d2a4d5d3f6441889ca5889c638ec998',
        paramKey: '',
        paramName: '发射功率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.1,
        valueUnit: 'dBm',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'S_BUC',
    deviceId: '26070101',
    deviceStatus: 'OFF_LINE',
    name: 'S-BUC',
  },
  {
    bodyList: [
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 18208,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'd3ea6f4e52d84a1196757d43a577e5a1',
        paramKey: '',
        paramName: '输入频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.001,
        valueUnit: 'MHz',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 0,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 18210,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: 'd3ea6f4e52d84a1196757d43a577e5a1',
        paramKey: '',
        paramName: '通道增益',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'XZC',
    deviceId: '26030105',
    deviceStatus: 'OFF_LINE',
    name: 'X校零变频器',
  },
  {
    bodyList: [
      {
        bindBodyId: 18257,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'a93d83ca59734f06b65d914e29f0fc72',
        byteType: 'I32_LE',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 18262,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '24d77e70d1154ac493a65236511bd741',
        paramKey: '',
        paramName: '输入频率',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 0.0001,
        valueUnit: 'MHz',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 18259,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: '878f0ed1e43243a58b6b3d4d4c9f6fa3',
        byteType: 'I8',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 18264,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 1,
        loopCount: 1,
        loopParse: 1,
        originUuid: '24d77e70d1154ac493a65236511bd741',
        paramKey: '',
        paramName: '通道增益',
        paramType: 'VALUE',
        patternUuid: '',
        selectConfig: [],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: 'dB',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'SZC',
    deviceId: '26030101',
    deviceStatus: 'OFF_LINE',
    name: 'S校零变频器',
  },
  {
    bodyList: [
      {
        bindBodyId: 2522,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'a5cea0ef3fcf475eadc9396b4d23478b',
        byteType: 'BIT',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 2487,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 0,
        loopCount: 2,
        loopParse: 1,
        originUuid: '0f0eacfc10f041439752016e46230358',
        paramKey: 'CPB_JX_5',
        paramName: 'X遥测和路',
        paramType: 'SELECT',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '01',
            success: false,
            value: '左旋',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '10',
            success: false,
            value: '右旋',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '00',
            success: false,
            value: '无效',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
      {
        bindBodyId: 2523,
        bindBodyInfo: null,
        bindUnitInfo: null,
        bindUnitUuid: 'a5cea0ef3fcf475eadc9396b4d23478b',
        byteType: 'BIT',
        early: false,
        earlyRange: {
          max: 0,
          min: 0,
        },
        id: 2488,
        ifSet: 1,
        indexType: 'NOTHING',
        joinLen: false,
        joinVerify: false,
        loopBuild: 0,
        loopCount: 2,
        loopParse: 1,
        originUuid: '0f0eacfc10f041439752016e46230358',
        paramKey: 'CPB_JX_6',
        paramName: 'X跟踪和路',
        paramType: 'SELECT',
        patternUuid: '',
        selectConfig: [
          {
            deviceWarn: false,
            key: '01',
            success: false,
            value: '左旋',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '10',
            success: false,
            value: '右旋',
            warn: false,
          },
          {
            deviceWarn: false,
            key: '00',
            success: false,
            value: '无效',
            warn: false,
          },
        ],
        showGplot: true,
        value: '',
        valueRange: {
          max: 0,
          min: 0,
        },
        valueStep: 1,
        valueUnit: '',
        verifyType: '',
        virtualField: false,
      },
    ],
    device: 'CPB',
    deviceId: '26FF0101',
    deviceStatus: 'OFF_LINE',
    name: '信道插箱',
  },
  {
    bodyList: [],
    device: 'PDU1',
    deviceId: '26140101',
    deviceStatus: 'OFF_LINE',
    name: 'PDU1',
  },
  {
    bodyList: [],
    device: 'PDU2',
    deviceId: '26140102',
    deviceStatus: 'OFF_LINE',
    name: 'PDU2',
  },
  {
    bodyList: [],
    device: 'PDU3',
    deviceId: '26140103',
    deviceStatus: 'OFF_LINE',
    name: 'PDU3',
  },
  {
    bodyList: [],
    device: 'XSBPQ',
    deviceId: '26080101XSBPQ',
    deviceStatus: 'OFF_LINE',
    name: 'X上变频器',
  },
  {
    bodyList: [],
    device: 'XSBPQ',
    deviceId: '26080101XSBPQ',
    deviceStatus: 'OFF_LINE',
    name: 'X上变频器',
  },
  {
    bodyList: [],
    device: 'XSCSBPQ',
    deviceId: '26080101XSCSBPQ',
    deviceStatus: 'OFF_LINE',
    name: '数传测试变频器',
  },
];
