/*
 * @Author: WangXin
 * @Date: 2023-02-08 14:53:10
 * @LastEditors: WangXin
 * @LastEditTime: 2023-03-14 23:03:39
 * @FilePath: \设备拓扑图\src\views\EquipmentManagement\equipment-SW.js
 * @Description:四维七台河站拓扑图
 *
 * Copyright (c) 2023 by YuXing, All Rights Reserved.
 */
import { randomWord } from '../../utils/utils';
const topologyElement = [
  {
    id: 1,
    type: 'equipment',
    parent_id: null,
    children_id: [113, 111],
    equipment_name: 'X校零变频器',
    device_key: 'XZC',
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '8400.5000MHZ',
      },
      {
        label: '增益',
        value: '30db',
      },
    ],
    style: {
      top: 30,
      left: 30,
      width: 175,
      height: 102,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: 'i73fqncj-taf7-9kyb-x4t9-iwr7jfx88ryf',
  },
  {
    id: 2,
    type: 'equipment',
    parent_id: null,
    children_id: [112, 114],
    equipment_name: 'S校零变频器',
    device_key: 'SZC',
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    s_fed: true,
    equipment_details: [
      {
        label: '频率',
        value: '8400.5000MHZ',
      },
      {
        label: '增益',
        value: '30db',
      },
    ],
    style: {
      top: 450,
      left: 30,
      width: 175,
      height: 102,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: 'lmiiy5mc-177s-r3pe-d68z-pgadeqma5nby',
  },
  {
    id: 3,
    parent_id: null,
    children_id: [112, 111],
    type: 'img',
    status: 'OFF_LINE',
    url: '/img/tianxian.1407abea.png',
    style: {
      top: 170,
      left: 30,
      width: 177,
      height: 211,
      color: '#61666A',
    },
    key: 'higtzgx2-3358-tn8e-ec72-x8xhgvm9y59r',
  },
  {
    id: 4,
    type: 'line-straight',
    parent_id: 108,
    children_id: 100,
    line_points: '0 0,0 30',
    status: 'OFF_LINE',
    arrow_transform: 'translate(0 30) rotate(-90)',
    line_start_arrow_transform: 'translate(0 0)  rotate(90)',
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 130,
      left: 117,
      width: 29,
      color: '#3474E4',
    },
    key: 'f1cawci7-szwm-j1nc-638d-17m4yj39cv8h',
  },
  {
    id: 5,
    type: 'line-straight',
    parent_id: 109,
    children_id: 110,
    line_points: '0 0,0 30',
    s_fed: true,
    status: 'OFF_LINE',
    arrow_transform: 'translate(0 30) rotate(-90)',
    line_start_arrow_transform: 'translate(0 0)  rotate(90)',
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 380,
      left: 117,
      width: 29,
      color: '#3474E4',
    },
    key: 'jy6frdy6-g9bw-diyg-yxew-hmyfdp481dm9',
  },
  {
    id: 6,
    status: 'OFF_LINE',
    type: 'round_rect',
    text: 'X频段馈源',
    style: {
      width: 47,
      height: 338,
      top: 10,
      left: 229,
      color: '#167AFF',
      background: 'var(--yx-background-3)',
      border: '2px solid #FFFFFF',
      borderRadius: [20],
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '35px',
    },
    key: 'wnrrbm6t-tmvl-8hj9-khtx-2f6za34dqdgg',
  },
  {
    id: 7,
    status: 'OFF_LINE',
    type: 'round_rect',
    text: 'S频段馈源',
    style: {
      width: 47,
      height: 296,
      top: 370,
      left: 229,
      background: 'var(--yx-background-3)',
      border: '2px solid #FFFFFF',
      color: '#07D0D0',
      borderRadius: [20],
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '35px',
    },
    key: 'vrxvrv3r-qfcv-s5ao-gprg-b52tl7csa5xs',
  },
  {
    id: 8,
    type: 'arrow',
    children_id: 9,
    status: 'OFF_LINE',
    parent_id: 1,
    style: {
      top: 30,
      left: 276,
      width: 10,
      color: 'var(--yx-font-4)',
    },
    key: 'kuwipn79-m41p-uay9-lhmn-nnz8f2c9pa2l',
  },
  {
    id: 9,
    children_id: 10,
    status: 'OFF_LINE',
    parent_id: 1,
    type: 'arrow',
    style: {
      top: 73,
      left: 276,
      width: 10,
      color: '#C3C9D2',
      transform: '',
    },
    key: 'tm5bp887-8t50-2oyo-a3xs-xp1vh05chkj3',
  },
  {
    id: 10,
    type: 'arrow',
    status: 'OFF_LINE',
    children_id: 11,
    parent_id: 1,
    style: {
      top: 156,
      left: 274,
      width: 10,
      color: '#3474E4',
      transform: 'translate(11,0) rotate(180)',
    },
    key: 'p9lskzeb-c4p7-j3sb-2vlz-xc47qosega3d',
  },
  {
    id: 11,
    type: 'arrow',
    children_id: 12,
    status: 'OFF_LINE',
    parent_id: 1,
    style: {
      top: 206,
      left: 274,
      width: 10,
      color: '#C3C9D2',
      transform: 'translate(11,0) rotate(180)',
    },
    key: '9oi8xase-qjmp-c2z3-ch3l-ph18vlox4p4o',
  },
  {
    id: 12,
    type: 'arrow',
    children_id: 13,
    status: 'OFF_LINE',
    parent_id: 1,
    style: {
      top: 275,
      left: 274,
      width: 10,
      color: '#3474E4',
      transform: 'translate(11,0) rotate(180)',
    },
    key: 'a9wnhonf-xd1b-5oil-hr2n-7fsxoiqo2rws',
  },
  {
    id: 13,
    type: 'arrow',
    children_id: 14,
    status: 'OFF_LINE',
    parent_id: 1,
    style: {
      top: 320,
      left: 274,
      width: 10,
      color: '#C3C9D2',
      transform: 'translate(11,0) rotate(180)',
    },
    key: '6sesfien-osfu-ljq5-imqs-koict71lvvyh',
  },
  {
    id: 14,
    type: 'arrow',
    parent_id: 2,
    status: 'OFF_LINE',
    children_id: 'r6zl0am8-8vme-20bx-0tbj-b3ugp1o7dt12',
    s_fed: true,
    style: {
      top: 400,
      left: 276,
      width: 10,
      color: '#3474E4',
    },
    key: 'nfcoq2ki-hrng-hxe1-79hh-7665madufkke',
  },
  {
    id: 15,
    type: 'arrow',
    s_fed: true,
    parent_id: 2,
    status: 'OFF_LINE',
    children_id: 'rgii4gst-88s2-s3gn-8fke-5e3e7k1t4cfv',
    style: {
      top: 450,
      left: 276,
      width: 10,
      color: '#C3C9D2',
      transform: '',
    },
    key: 'w2xemmbs-a2qc-r60y-decm-9kzahcyom7vq',
  },
  {
    id: 16,
    type: 'arrow',
    parent_id: 2,
    children_id: 'pgslnt2c-wmod-rhhj-0vam-mc63h8kt26ce',
    status: 'OFF_LINE',
    s_fed: true,
    style: {
      top: 500,
      left: 274,
      width: 10,
      color: '#3474E4',
      transform: 'translate(11,0) rotate(180)',
    },
    key: 'f1tfho6w-c2pf-yb5p-hh9x-5q9ctulagy9m',
  },
  {
    id: 17,
    type: 'arrow',
    parent_id: 2,
    children_id: '4xmrqyv2-47tu-badc-b0p9-imowowp2dq9i',
    status: 'OFF_LINE',
    s_fed: true,
    style: {
      top: 550,
      left: 274,
      width: 10,
      color: '#C3C9D2',
      transform: 'translate(11,0) rotate(180)',
    },
    key: 'towi1ict-pg4p-591n-7iyw-obbma46gc5t9',
  },
  {
    id: 18,
    type: 'arrow',
    parent_id: 2,
    children_id: 'vuqo2rvk-icb5-0qzg-ytj5-sd9prvsyjrv2',
    status: 'OFF_LINE',
    s_fed: true,
    style: {
      top: 600,
      left: 274,
      width: 10,
      color: '#3474E4',
      transform: 'translate(11,0) rotate(180)',
    },
    key: '851fq7db-u6a3-psam-om77-x9guc5em02nb',
  },
  {
    id: 19,
    type: 'arrow',
    parent_id: 2,
    status: 'OFF_LINE',
    s_fed: true,
    children_id: 'loqxskfi-ntls-l2db-xnxe-w2eslwi1nj4r',
    style: {
      top: 645,
      left: 274,
      width: 10,
      color: '#C3C9D2',
      transform: 'translate(11,0) rotate(180)',
    },
    key: '8xwdmb6b-3lp6-kjmt-lyta-jmc6a7e1vv9f',
  },
  {
    id: 20,
    type: 'round_rect_mini',
    text: 'LHPC',
    children_id: 'rbgruh9l-us85-rpab-h54t-bsm2d1eqz6ke',
    status: 'OFF_LINE',
    parent_id: 3,
    style: {
      top: 18,
      left: 296,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: '7arps38u-bs7u-neu8-e7jl-nc8xdkp58hir',
  },
  {
    id: 21,
    type: 'round_rect_mini',
    children_id: 68,
    status: 'OFF_LINE',
    parent_id: 4,
    text: 'RHPC',
    style: {
      top: 62,
      left: 296,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      background: '#F1F4F7',
      border: '1px solid #FFFFFF',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: 'axz460tc-isbd-jjil-kso3-dpawq67ii17r',
  },
  {
    id: 22,
    type: 'round_rect_mini',
    text: 'LHPC',
    children_id: 17,
    status: 'OFF_LINE',
    parent_id: 5,
    style: {
      top: 144,
      left: 296,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: '8cl8svs5-pky7-ak6t-vu5z-8uo8t2spfput',
  },
  {
    id: 23,
    type: 'round_rect_mini',
    status: 'OFF_LINE',
    text: 'RHPC',
    children_id: 18,
    parent_id: 6,
    style: {
      top: 196,
      left: 296,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: '9u1ohse3-4yes-3ddt-krhr-vj1oueh9sm2b',
  },
  {
    id: 24,
    type: 'round_rect_mini',
    status: 'OFF_LINE',
    children_id: 19,
    parent_id: 7,
    text: 'LHPC',
    style: {
      top: 265,
      left: 296,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: '4ogt6k37-1ta2-gcif-kar3-q5sp6syqayhd',
  },
  {
    id: 25,
    type: 'round_rect_mini',
    text: 'RHPC',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 310,
      left: 296,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: 'mjxwnkhl-vw6i-t3i2-eq4v-8mo7wp0e2ij3',
  },
  {
    id: 26,
    type: 'round_rect_mini',
    parent_id: 'gd7jm08i-33hq-rwzw-yp6v-f9l3w4ibloy5',
    status: 'OFF_LINE',
    children_id: 75,
    text: 'LHPC',
    s_fed: true,
    style: {
      top: 390,
      left: 296,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: 'bltr03fd-wy9g-5e1j-whj1-yoyst9c5vrxc',
  },
  {
    id: 27,
    type: 'round_rect_mini',
    parent_id: 'ji1nl840-0mmc-ufj7-i2i8-e87o413z2a7k',
    children_id: 76,
    text: 'RHPC',
    s_fed: true,
    status: 'OFF_LINE',
    style: {
      top: 440,
      left: 296,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: '8sf0152n-8wtr-ptk8-xk3a-383nd3qn1t1t',
  },
  {
    id: 28,
    type: 'round_rect_mini',
    s_fed: true,
    status: 'OFF_LINE',
    parent_id: '25nc2jnh-jo5s-tw35-hvfk-j4f7ztw5d8dd',
    children_id: 71,
    text: 'LHPC',
    style: {
      top: 490,
      left: 296,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: 'cfvvarig-pq9z-4ofq-k94p-s6jrf189kmwg',
  },
  {
    id: 29,
    type: 'round_rect_mini',
    parent_id: '1qy8s0a3-nlqe-bxjj-rshq-kaf3n4py7vcf',
    s_fed: true,
    status: 'OFF_LINE',
    children_id: 72,
    text: 'RHPC',
    style: {
      top: 540,
      left: 296,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: '3remmamq-cvbo-8iym-86ej-1y15ygyskbh8',
  },
  {
    id: 30,
    type: 'round_rect_mini',
    parent_id: 'wwksx3eb-4uin-wnr7-agir-fw9pg2z74dhn',
    s_fed: true,
    status: 'OFF_LINE',
    children_id: 73,
    text: 'LHPC',
    style: {
      top: 590,
      left: 296,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: '2exfawvf-c5kd-e2sh-6vfr-i828u4ji0w6p',
  },
  {
    id: 31,
    type: 'round_rect_mini',
    parent_id: '21tvxecs-gqch-66r8-p29k-e9bq3j73slm7',
    s_fed: true,
    status: 'OFF_LINE',
    children_id: 74,
    text: 'RHPC',
    style: {
      top: 635,
      left: 296,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
    key: 'm95tbu6h-koxe-inpb-m0h1-lmdy8pykjcd8',
  },
  {
    id: 32,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_S_1',
    paramValue: 'ACU_JX_S_1',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 34,
    polarity: {
      0: [33, 20, 8],
      1: [35, 21, 9],
    },
    direction: {
      left: '0',
      right: '1',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 40,
      left: 400,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: '8s15pvtj-6f27-9k1w-j7ys-aa4bjonjus6g',
  },
  {
    id: 33,
    type: 'line-straight',
    parent_id: 9,
    status: 'OFF_LINE',
    children_id: 16,
    text: 'RHPC',
    line_points: '0 0,21 0, 21 10',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    line_circle: {
      cx: 30,
      cy: 9.5,
    },
    style: {
      top: 30,
      left: 368,
      width: 20,
      height: 24,
      color: '#3474E4',
    },
    key: '2gh7jtpw-0r7k-tmkh-b00d-49p17q8gebih',
  },
  {
    id: 34,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    animateStartRight: true,
    no_arrow: true,
    no_circle: true,
    style: {
      top: 50,
      left: 410,
      width: 29,
      color: '#3474E4',
    },
    key: 'jnxub6hy-ltgu-ug4d-erwd-19gy15cpgyvn',
  },
  {
    id: 35,
    parent_id: 10,
    status: 'OFF_LINE',
    children_id: 16,
    type: 'line-straight',
    text: 'RHPC',
    line_points: '0 0,21 0,21 -12',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    no_circle: false,
    line_circle: {
      cx: 30,
      cy: -12,
    },
    style: {
      top: 73,
      left: 368,
      width: 22,
      height: 24,
      color: '#C3C9D2',
    },
    key: 'tbxgv7sx-wv63-j9fb-xfva-ytzer1a24j2h',
  },
  {
    id: 36,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    no_arrow: true,
    no_circle: true,
    style: {
      top: 50,
      left: 377,
      width: 29,
      color: '#3474E4',
    },
    key: '5pdn1xdu-qtda-hsfi-z2mk-mp32f0m3wg92',
  },
  {
    id: 37,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 46,
      left: 353,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: 'mygs5kif-vf5e-panw-rcfs-kure7lj8vivn',
  },
  {
    id: 38,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_S_2',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 135,
    polarity: {
      0: [39, 22, 10, 40],
      1: [43, 42],
    },
    direction: {
      left: '0',
      right: '1',
    },
    rotate: {
      left: -100,
      right: 263,
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 144,
      left: 400,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: 'uwuv8i21-gp5o-xys7-nvt2-eqear0ubf35s',
  },
  {
    id: 39,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,15 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    animateStartRight: true,
    no_arrow: true,
    no_circle: true,
    style: {
      top: 153,
      left: 368,
      width: 29,
      color: '#3474E4',
    },
    key: 'wiiffca8-parq-f7hb-jh90-23uwf2z12iyk',
  },
  {
    id: 40,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 -13,18 -13',
    arrow_transform: 'translate(18 -13) rotate(180)',
    line_start: 'arrow',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 153,
      left: 409,
      width: 29,
      color: '#3474E4',
    },
    key: 'qk8nwe6c-d4qu-edge-6gyd-vgbidcac5yb5',
  },
  {
    id: 41,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 150,
      left: 435,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: 'yr9mbly4-4yp9-jsn9-kcjh-f7nlovzl8s6m',
  },
  {
    id: 42,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 153.5,
      left: 410,
      width: 29,
      color: '#3474E4',
    },
    key: 'l9mm5kkp-6qx6-h4ny-l9ge-lm5ua4jtb7nd',
  },
  {
    id: 43,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 8,8 8,8 22 ,5 22',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 160,
      left: 410,
      width: 29,
      color: '#3474E4',
    },
    key: 'pgh70lk6-j7px-e6vs-swdx-tfxl9cr2adhb',
  },
  {
    id: 44,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_S_3',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 135,
    polarity: {
      0: [45, 46, 23, 11],
      1: [52],
    },
    direction: {
      left: '0',
      right: '1',
    },
    rotate: {
      left: -104,
      right: 276,
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 195,
      left: 400,
      width: 20,
      height: 20,
      rotate: 90,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: 'om1nia4z-0hx1-x0qu-78hj-r9ftg90r17he',
  },
  {
    id: 45,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,15 0',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 206,
      left: 370,
      width: 29,
      color: '#3474E4',
    },
    key: 'swgjn6g7-jdwm-6pd9-eosl-igdkpvdu01rt',
  },
  {
    id: 46,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 -2,20 -2',
    arrow_transform: 'translate(20 -2) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 192,
      left: 409,
      width: 29,
      color: '#3474E4',
    },
    key: '0ucc5wrb-7pv4-kl8k-six9-6vwu7yoglwvs',
  },
  {
    id: 47,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 124,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X-HPA',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 35,
      left: 450,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: '95e8v663-efur-hkwd-sywu-5qy9cdm31hvv',
  },
  {
    id: 48,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 125,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X和场放左',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 110,
      left: 450,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'zxpwyfom-cwm6-imvo-6usb-o6ojvjqxozpb',
  },
  {
    id: 49,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 126,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X和场放右',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 172,
      left: 450,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'ujc3vxog-qz5p-yq4s-wyjk-6ds4o9tpwst3',
  },
  {
    id: 50,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 99,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X和场设备',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 230,
      left: 450,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'q17au3wv-b3sf-oisj-e0rl-flemwhg2udsg',
  },
  {
    id: 51,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 122,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X差场放',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 285,
      left: 450,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'avig3nlg-uob0-xvgc-3b76-pn5e7gwq7h7k',
  },
  {
    id: 52,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 15,20 15',
    arrow_transform: 'translate(20 15) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 215,
      left: 408,
      width: 29,
      color: '#3474E4',
    },
    key: 'x4jpuay3-koj2-1n2m-xudw-ac4ummlh1syq',
  },
  {
    id: 53,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_S_4',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 55,
    polarity: {
      0: [54, 24, 12],
      1: [56, 25, 13],
    },
    direction: {
      left: '0',
      right: '1',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 290,
      left: 400,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: 'nkc102q7-iy8h-8i9w-c83p-dn3btdfvamet',
  },
  {
    id: 54,
    type: 'line-straight',
    parent_id: 9,
    status: 'OFF_LINE',
    children_id: 16,
    text: 'RHPC',
    line_points: '0 0,21 0, 21 10',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    line_circle: {
      cx: 30,
      cy: 9.5,
    },
    style: {
      top: 275,
      left: 368,
      width: 20,
      height: 24,
      color: '#3474E4',
    },
    key: 'ovye1v5k-ocfm-gslb-rxnp-zucapm7o71jw',
  },
  {
    id: 55,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    animateStartRight: true,
    no_arrow: true,
    no_circle: true,
    style: {
      top: 300,
      left: 410,
      width: 29,
      color: '#3474E4',
    },
    key: '8r35jl2d-375n-7dew-e38a-5o3tr0cew8wo',
  },
  {
    id: 56,
    parent_id: 10,
    status: 'OFF_LINE',
    children_id: 16,
    type: 'line-straight',
    text: 'RHPC',
    line_points: '0 0,21 0,21 -12',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    no_circle: false,
    line_circle: {
      cx: 30,
      cy: -12,
    },
    style: {
      top: 322,
      left: 368,
      width: 22,
      height: 24,
      color: '#C3C9D2',
    },
    key: 'efu9lu8u-wvoi-36dw-ih56-8wosw1ieyh52',
  },
  {
    id: 57,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    no_arrow: true,
    no_circle: true,
    style: {
      top: 300,
      left: 377,
      width: 29,
      color: '#3474E4',
    },
    key: 'gkvpakhe-zabs-0oga-plr5-75m4m42w5rdr',
  },
  {
    id: 58,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 296,
      left: 353,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: 'bf44afyl-j2uk-kpu1-k6af-qciz8o9wxvou',
  },
  {
    id: 59,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 101,
    s_fed: true,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'S-HPA',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 410,
      left: 450,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: '3uv6u73y-u5rj-pkln-mp4y-mxh87bh9l4yy',
  },
  {
    id: 60,
    type: 'equipment',
    s_fed: true,
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: [107, 108, 109],
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'S和场放',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 510,
      left: 450,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: '1cw7o7vx-b67b-6b49-4er9-x1om6pdbhlsi',
  },
  {
    id: 61,
    type: 'equipment',
    s_fed: true,
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 102,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'S差场放',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 610,
      left: 450,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'f5qtu2jz-kd73-8hv1-8ysc-1qpi3f82y8pu',
  },
  {
    id: 62,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_2',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    s_fed: true,
    children_id: 64,
    polarity: {
      1: [63, 28, 16],
      2: [65, 29, 17],
    },
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 515,
      left: 400,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: 'o9bkkzph-bhws-ljt5-3hov-qmzrxq7srhdl',
  },
  {
    id: 63,
    type: 'line-straight',
    parent_id: 9,
    status: 'OFF_LINE',
    children_id: 16,
    s_fed: true,
    text: 'RHPC',
    line_points: '0 0,21 0, 21 10',
    no_arrow: true,
    animateStartRight: true,
    line_circle: {
      cx: 30,
      cy: 9.5,
    },
    style: {
      top: 500,
      left: 368,
      width: 20,
      height: 24,
      color: '#3474E4',
    },
    key: 'tabbe9g4-19wh-qw7n-tpd1-4b0n1p6p65qy',
  },
  {
    id: 64,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    s_fed: true,
    line_points: '0 0,20 0',
    arrow_transform: 'translate(20 0) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 525,
      left: 410,
      width: 29,
      color: '#3474E4',
    },
    key: 'eepwjlug-3q7w-8agd-vpoz-hcsjoonwkasl',
  },
  {
    id: 65,
    parent_id: 10,
    status: 'OFF_LINE',
    children_id: 16,
    type: 'line-straight',
    s_fed: true,
    text: 'RHPC',
    line_points: '0 0,21 0,21 -12',
    animateStartRight: true,
    no_circle: false,
    no_arrow: true,
    line_circle: {
      cx: 30,
      cy: -12,
    },
    style: {
      top: 552,
      left: 368,
      width: 22,
      height: 24,
      color: '#C3C9D2',
    },
    key: 'd8jro8mm-okpx-0vsl-xtrm-5atzjsb7rx3j',
  },
  {
    id: 66,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    no_arrow: true,
    no_circle: true,
    style: {
      top: 525,
      left: 377,
      width: 29,
      color: '#3474E4',
    },
    key: 'qgh7t1r8-aadb-gfqt-k1vz-e92cooc29cie',
  },
  {
    id: 67,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 520,
      left: 353,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: '5n0a5xqg-x9o3-ogv4-qy7e-5d6ipbaz8vui',
  },
  {
    id: 68,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_1',
    paramValue: 'ACU_JX_X_5_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    s_fed: true,
    children_id: 70,
    polarity: {
      0: [69, 26, 14],
      1: [71, 27, 15],
    },
    direction: {
      left: '0',
      right: '1',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 415,
      left: 400,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: 'cvcw8k6y-h8f2-q1sd-55vq-jaltswfou3k9',
  },
  {
    id: 69,
    type: 'line-straight',
    parent_id: 9,
    status: 'OFF_LINE',
    children_id: 16,
    text: 'RHPC',
    s_fed: true,
    line_points: '0 0,21 0, 21 10',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    line_circle: {
      cx: 30,
      cy: 9.5,
    },
    style: {
      top: 400,
      left: 368,
      width: 20,
      height: 24,
      color: '#3474E4',
    },
    key: 'tn4iade0-e50f-7yll-pb8h-k8np9tmh7c4b',
  },
  {
    id: 70,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    s_fed: true,
    line_points: '0 0,20 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    animateStartRight: true,
    no_arrow: true,
    no_circle: true,
    style: {
      top: 425,
      left: 410,
      width: 29,
      color: '#3474E4',
    },
    key: '3ap6x4or-cobu-qjmx-vxb6-ojtwpxka01t4',
  },
  {
    id: 71,
    parent_id: 10,
    status: 'OFF_LINE',
    children_id: 16,
    s_fed: true,
    type: 'line-straight',
    text: 'RHPC',
    line_points: '0 0,21 0,21 -12',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    no_circle: false,
    line_circle: {
      cx: 30,
      cy: -12,
    },
    style: {
      top: 452,
      left: 368,
      width: 22,
      height: 24,
      color: '#C3C9D2',
    },
    key: '3gdtk5k9-tp52-yhsw-tshm-jj15jyw2gx4u',
  },
  {
    id: 72,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    no_arrow: true,
    no_circle: true,
    style: {
      top: 425,
      left: 377,
      width: 29,
      color: '#3474E4',
    },
    key: 'wgvu7512-1r41-pk5b-on7i-ujxy6en2xuai',
  },
  {
    id: 73,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 420,
      left: 353,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: '6ly9w7ey-gq27-iopf-zmud-i83dioyj8ilo',
  },
  {
    id: 74,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_74',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    s_fed: true,
    children_id: 76,
    polarity: {
      1: [75, 30, 18],
      2: [77, 31, 19],
    },
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 615,
      left: 400,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: 'xkkgecbp-h9hr-hckd-1flr-57rlsebhqiwf',
  },
  {
    id: 75,
    type: 'line-straight',
    parent_id: 9,
    status: 'OFF_LINE',
    children_id: 16,
    text: 'RHPC',
    line_points: '0 0,21 0, 21 10',
    no_arrow: true,
    s_fed: true,
    animateStartRight: true,
    line_circle: {
      cx: 30,
      cy: 9.5,
    },
    style: {
      top: 600,
      left: 368,
      width: 20,
      height: 24,
      color: '#3474E4',
    },
    key: '2e3bjxk2-lx9d-362u-4xwe-etozn0u7jkq1',
  },
  {
    id: 76,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    s_fed: true,
    line_points: '0 0,20 0',
    arrow_transform: 'translate(20 0) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 625,
      left: 410,
      width: 29,
      color: '#3474E4',
    },
    key: '5lj9xg78-722l-37d8-lxle-0bt75p3b3129',
  },
  {
    id: 77,
    parent_id: 10,
    s_fed: true,
    status: 'OFF_LINE',
    children_id: 16,
    type: 'line-straight',
    text: 'RHPC',
    line_points: '0 0,21 0,21 -12',
    animateStartRight: true,
    no_circle: false,
    no_arrow: true,
    line_circle: {
      cx: 30,
      cy: -12,
    },
    style: {
      top: 652,
      left: 368,
      width: 22,
      height: 24,
      color: '#C3C9D2',
    },
    key: 'ffcv013i-k181-x6uk-gmah-27mrjh4x4j6w',
  },
  {
    id: 78,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    no_arrow: true,
    no_circle: true,
    style: {
      top: 625,
      left: 377,
      width: 29,
      color: '#3474E4',
    },
    key: 'gsd5lps6-oj4v-n6jc-j7ju-exk5utamdxhe',
  },
  {
    id: 79,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 620,
      left: 353,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: '8lfxiio5-hiya-kowd-722w-3nlw6mckm6n9',
  },
  {
    id: 80,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 87,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X上变频器',
    device_key: 'XSBPQ',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 25,
      left: 670,
      width: 134,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: '3empebft-2bmi-ztr7-cf7v-uwrjc2jma1cp',
  },
  {
    id: 81,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 88,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '数传测试变频器',
    device_key: 'XSCSBPQ',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 65,
      left: 670,
      width: 170,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: '23r2wxt1-tmtw-mgro-grq5-46pi6lzbnmdg',
  },
  {
    id: 82,
    type: 'rect-mini',
    text: '功分器',
    parent_id: 28,
    status: 'OFF_LINE',
    equipment_name: '功分器1',
    children_id: 143,
    style: {
      top: 105,
      left: 670,
      width: 34,
      height: 78,
      color: '#4B4F55',
      background: '#F9FBFC',
      borderRadius: [2],
      fontSize: '14px',
    },
    key: 'tg842io6-avep-7nhf-r3hg-qlbwpb545vcv',
  },
  {
    id: 83,
    type: 'rect-mini',
    text: '功分器',
    parent_id: 28,
    status: 'OFF_LINE',
    equipment_name: '功分器1',
    children_id: 130,
    style: {
      top: 205,
      left: 670,
      width: 34,
      height: 78,
      color: '#4B4F55',
      background: '#F9FBFC',
      borderRadius: [2],
      fontSize: '14px',
    },
    key: 'htl8c3qc-aou6-qgad-ohpn-zsar8lw7vb2p',
  },
  {
    id: 84,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: [100, 110],
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'S上变频器',
    equipment_icon: 'add-play',
    s_fed: true,
    status: 'null',
    equipment_details: [],
    style: {
      top: 410,
      left: 670,
      width: 142,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'ceigskxx-qks4-ews5-yjos-un1gh601oiqe',
  },
  {
    id: 85,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 28,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'S小环变频器',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 460,
      left: 670,
      width: 142,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'xxy92c9p-4pi7-swmq-bocz-besapo9vkaq1',
  },
  {
    id: 86,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 114,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'S合成网络',
    equipment_icon: 'add-play',
    s_fed: true,
    status: 'null',
    equipment_details: [],
    style: {
      top: 610,
      left: 670,
      width: 142,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'egckud6y-ym58-f6ic-1x6x-xccv1p8oebx6',
  },
  {
    id: 87,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,-15 0,-15 8,-42 8',
    arrow_transform: 'translate(-42 8) rotate(0)',
    no_circle: true,
    style: {
      top: 35,
      left: 670,
      width: 29,
      color: '#3474E4',
    },
    key: '5827ihrj-d3v8-mykt-qzti-koua41pcrg5q',
  },
  {
    id: 88,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,-75 0,-75 12',
    arrow_transform: 'translate(-75 13) rotate(-90)',
    no_circle: true,
    style: {
      top: 80,
      left: 670,
      width: 29,
      color: '#3474E4',
    },
    key: '0m621wsd-hqu3-3jjj-6o4z-9snxa3p5y6o8',
  },
  {
    id: 89,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,-15 0,-15 10,-19 10',
    arrow_transform: 'translate(0 0) rotate(180)',
    no_circle: true,
    animateStartRight: true,
    style: {
      top: 140,
      left: 670,
      width: 29,
      color: '#3474E4',
    },
    key: 'w8jtaelb-ikeg-4cyv-b448-5kjmwdggdsda',
  },
  {
    id: 90,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_90',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 135,
    polarity: {
      1: [91, 89],
      2: [94, 89],
    },
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 150,
      left: 610,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: 'n63mlsrc-kyij-5qrn-imhw-x6hdc5yojxgg',
  },
  {
    id: 91,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,17 0,17 13',
    no_circle: true,
    no_arrow: true,
    style: {
      top: 125,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: '52r4pwvo-o83w-rtsc-6u22-wtrvcimeju98',
  },
  {
    id: 92,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    no_arrow: true,
    no_circle: true,
    style: {
      top: 160,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: '1kvtdbfh-g75l-o1b5-rfa6-fprfp21c25fk',
  },
  {
    id: 93,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 156,
      left: 560,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: 'w35x0doz-35o7-h6ya-plcs-gn590du2xqkq',
  },
  {
    id: 94,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 29,6 29',
    no_circle: true,
    no_arrow: true,
    style: {
      top: 170,
      left: 619,
      width: 29,
      color: '#3474E4',
    },
    key: 'jgscatcp-apq4-770s-6rkk-l3pqg3k2gper',
  },
  {
    id: 95,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_95',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 98,
    polarity: {
      1: [97],
      2: [99],
    },
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 220,
      left: 630,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: '29d9176h-wb3a-ylka-p6cj-guj30x2a6uai',
  },
  {
    id: 96,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,27 0,27 20',
    no_circle: true,
    no_arrow: true,
    style: {
      top: 185,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: '3mkl3cx1-6njy-wawz-4dt0-ixqk4ymg2wvj',
  },
  {
    id: 97,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,27 0,27 20',
    no_circle: true,
    no_arrow: true,
    style: {
      top: 185,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: 'nro3afnk-r8ga-lpg7-b7ba-adarx107zs38',
  },
  {
    id: 98,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,10 0',
    no_circle: true,
    arrow_transform: 'translate(10 0) rotate(180)',
    style: {
      top: 230,
      left: 650,
      width: 29,
      color: '#3474E4',
    },
    key: '366d3gdj-c35t-9rkr-31fo-pc6olq7g4zif',
  },
  {
    id: 99,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,27.5 0,27.5 -5',
    no_circle: true,
    no_arrow: true,
    style: {
      top: 248,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: 'i3rvb460-fh6u-imyc-780y-ws5k6ajywoca',
  },
  {
    id: 100,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,42 0',
    no_circle: true,
    s_fed: true,
    animateStartRight: true,
    arrow_transform: 'translate(0 0) rotate(0)',
    style: {
      top: 425,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: 'p4okhwpa-ctyd-mitn-wu6u-3wcbbpzns88g',
  },
  {
    id: 101,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 17,75 17',
    no_circle: true,
    s_fed: true,
    arrow_transform: 'translate(75 17) rotate(180)',
    style: {
      top: 442,
      left: 518,
      width: 29,
      color: '#3474E4',
    },
    key: 'pfegs8o6-o8qq-epd4-qbdc-qj86g7q2ktke',
  },
  {
    id: 102,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,42 0',
    no_circle: true,
    arrow_transform: 'translate(42 0) rotate(180)',
    style: {
      top: 625,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: 'ubqlrhxg-baya-1wzv-1gh9-2cwu5o3bvbrw',
  },
  {
    id: 103,
    type: 'round_rect',
    text: '1.2G矩阵',
    parent_id: [52, 53, 54],
    status: 'OFF_LINE',
    children_id: 104,
    style: {
      width: 47,
      height: 210,
      top: 10,
      left: 1256,
      color: '#334681',
      background: 'rgba(255,255,255,0.12)',
      border: '2px solid #fff',
      borderRadius: [20],
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '25px',
      wordBreak: 'break-all',
    },
    key: 'vyjr64uc-em6y-vkib-xlk3-7ye2odtyx4ha',
  },
  {
    id: 104,
    type: 'round_rect',
    parent_id: [27, 32, 49, 50, 48, 82, 92, 93],
    children_id: [113, 111, 174, 175],
    status: 'OFF_LINE',
    text: '70M矩阵',
    s_fed: true,
    style: {
      width: 47,
      height: 424,
      top: 237,
      left: 1256,
      color: '#334681',
      background: 'rgba(255,255,255,0.12)',
      border: '2px solid #fff',
      borderRadius: [20],
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '35px',
      wordBreak: 'break-all',
    },
    key: 'ntzsy3vq-xccy-jn2a-nurv-y1ysxdsmnwol',
  },
  {
    id: 105,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 112,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'S下变频器',
    equipment_icon: 'add-play',
    s_fed: true,
    status: 'null',
    equipment_details: [],
    style: {
      top: 510,
      left: 958,
      width: 142,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: '2jyxprml-2yqd-ep51-31md-k3pxyi56jpav',
  },
  {
    id: 106,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: null,
    s_fed: true,
    equipment_name: 'S测试上变频器',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 555,
      left: 958,
      width: 170,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: '4ynj5st6-eb0u-ud3p-h9le-omk90wq0llml',
  },
  {
    id: 107,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,185 0',
    no_circle: true,
    arrow_transform: 'translate(185 0) rotate(180)',
    style: {
      top: 524,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: 'x62uhggj-bfr0-i17b-rkdr-75vyh4rpeqce',
  },
  {
    id: 108,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 13,218 13',
    no_circle: true,
    arrow_transform: 'translate(218 13) rotate(180)',
    style: {
      top: 542,
      left: 518,
      width: 29,
      color: '#3474E4',
    },
    key: 'maispd4p-eyvt-i1u6-0vup-n8k4rnzr0q3d',
  },
  {
    id: 109,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 42',
    no_circle: true,
    arrow_transform: 'translate(0 42) rotate(-90)',
    style: {
      top: 522,
      left: 732,
      width: 29,
      color: '#3474E4',
    },
    key: 'pepu86oy-q5t4-dtjc-en5p-aidjrx63s5d4',
  },
  {
    id: 110,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,220 0',
    no_circle: true,
    arrow_transform: 'translate(220 0) rotate(180)',
    style: {
      top: 423,
      left: 813,
      width: 29,
      color: '#3474E4',
    },
    key: '3um74vf9-mmt3-f383-wx7a-uicrqfuviael',
  },
  {
    id: 111,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,220 0',
    no_circle: true,
    animateStartRight: true,
    arrow_transform: 'translate(0 0) rotate(0)',
    style: {
      top: 476,
      left: 813,
      width: 29,
      color: '#3474E4',
    },
    key: '2xunsh3d-a02u-5qg6-uy4o-ft1fy3y9crb8',
  },
  {
    id: 112,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,78 0',
    no_circle: true,
    s_fed: true,
    arrow_transform: 'translate(78 0) rotate(180)',
    style: {
      top: 522,
      left: 1100,
      width: 29,
      color: '#3474E4',
    },
    key: 'ziwjdhih-nu92-g2b2-flvb-5t72avg6ll59',
  },
  {
    id: 113,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    s_fed: true,
    line_points: '0 0,62 0',
    no_circle: true,
    animateStartRight: true,
    arrow_transform: 'translate(0 0) rotate(0)',
    style: {
      top: 570,
      left: 1133,
      width: 29,
      color: '#3474E4',
    },
    key: 'ncjb76cv-3j84-hhhl-v5xg-z8cvl2x1q2vs',
  },
  {
    id: 114,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,220 0',
    no_circle: true,
    s_fed: true,
    arrow_transform: 'translate(220 0) rotate(180)',
    style: {
      top: 625,
      left: 815,
      width: 29,
      color: '#3474E4',
    },
    key: '2qybgv33-chk5-9o72-gfvq-jc8aj3fsj7f0',
  },
  {
    id: 115,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 128,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X小环变频器',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 6,
      left: 957,
      width: 142,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'atg83i45-rf7l-r5j2-g7ow-s5rrx4h0gvot',
  },
  {
    id: 116,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 28,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '1.2G变频器左',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 85,
      left: 957,
      width: 145,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'lspnmuuo-3liy-a1vq-se33-3lo9gn81wkgb',
  },
  {
    id: 117,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 28,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '1.2G变频器右',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 130,
      left: 957,
      width: 145,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: '2tfobpi3-fkft-cb9u-vth8-qmin938sd1wl',
  },
  {
    id: 118,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 28,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '1.2G变频器备',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 170,
      left: 957,
      width: 145,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'qfh27qw2-b97p-kcr2-p14j-h0p8yc5nf3el',
  },
  {
    id: 119,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 28,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X下变频器左',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 210,
      left: 957,
      width: 142,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'm5wgw22j-3z6v-uy2p-j613-3od9715iu7lj',
  },
  {
    id: 120,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 28,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X下变频器左',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 250,
      left: 957,
      width: 142,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'j28re4bj-tbqo-53of-rvit-qo0ka4fj5xpu',
  },
  {
    id: 121,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 123,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '合成网络',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 287,
      left: 765,
      width: 142,
      height: 32,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'khaorf1i-7ijf-gkib-r8ao-bnwg8gfev7a9',
  },
  {
    id: 122,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,90 0',
    arrow_transform: 'translate(90 0) rotate(180)',
    no_circle: true,
    style: {
      top: 300,
      left: 585,
      width: 29,
      color: '#3474E4',
    },
    key: '5650y92x-6wl7-qi2u-fw2d-ylk05ojmksrd',
  },
  {
    id: 123,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,174 0',
    arrow_transform: 'translate(174 0) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 300,
      left: 907,
      width: 29,
      color: '#3474E4',
    },
    key: 'r2ntifm6-wcg0-lexx-alvy-ehlmhbo9eihy',
  },
  {
    id: 124,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 -8,218 -8',
    arrow_transform: 'translate(218 -8) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 34,
      left: 518,
      width: 29,
      color: '#3474E4',
    },
    key: 'g5lajq21-48ou-o1uq-2n2f-2bcv2avqnte8',
  },
  {
    id: 125,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 14',
    arrow_transform: 'translate(0 14) rotate(-90)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 142,
      left: 518,
      width: 29,
      color: '#3474E4',
    },
    key: 'jv0m6ekl-xns5-5i4e-ykvi-b3prpeg9wqbr',
  },
  {
    id: 126,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 12',
    arrow_transform: 'translate(0 12) rotate(-90)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 204,
      left: 518,
      width: 29,
      color: '#3474E4',
    },
    key: 'req2toqb-fwwo-f6ji-fgqb-64ud7cqe2bxn',
  },
  {
    id: 127,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,200 0,200 110,225 110',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 43,
      left: 805,
      width: 29,
      color: '#3474E4',
    },
    key: 'jw0bplgw-ciz8-eme1-jx83-hprbg7vok3ey',
  },
  {
    id: 128,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,45 0,45 130,78 130',
    arrow_transform: 'translate(78 130) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 22,
      left: 1099,
      width: 29,
      color: '#3474E4',
    },
    key: 'yfm5x2i4-dqzz-nlw6-ge7h-69dm15f4tbp0',
  },
  {
    id: 129,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,208 0',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 75,
      left: 840,
      width: 29,
      color: '#3474E4',
    },
    key: '8mcv7u4o-1k2j-1oy1-2fr1-p4usrmstsgh1',
  },
  {
    id: 130,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,125 0',
    arrow_transform: 'translate(125 0) rotate(180)',
    // animateStartRight: true,
    no_circle: true,
    style: {
      top: 265,
      left: 705,
      width: 29,
      color: '#3474E4',
    },
    key: 'ms3usngl-7hwu-p0hx-2l46-gg8qr4hpln26',
  },
  {
    id: 131,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_131',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 133,
    polarity: {
      1: [132],
      2: [134],
    },
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 181,
      left: 754,
      width: 20,
      height: 20,
      rotate: 0,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: '4w4w39lo-b0g3-mgxt-3fcw-6wn53dybgrxy',
  },
  {
    id: 132,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,29 0,29 10',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 160,
      left: 705,
      width: 29,
      color: '#3474E4',
    },
    key: 'iqs33qcd-v7ol-67vd-ysvg-k5nzjerzcdkf',
  },
  {
    id: 133,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,29 0,29 48',
    arrow_transform: 'translate(29 48) rotate(-90)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 190,
      left: 777,
      width: 29,
      color: '#3474E4',
    },
    key: '3rhz664j-stq9-d0pu-npb2-ibq9qq2ozzu3',
  },
  {
    id: 134,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,29 0,29 -30',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 250,
      left: 705,
      width: 29,
      color: '#3474E4',
    },
    key: 'fck6qn1o-5vw4-f2hs-1yt5-bprwxqeueqc7',
  },
  {
    id: 135,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,-10 0',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 190,
      left: 755,
      width: 29,
      color: '#3474E4',
    },
    key: '8t5233s8-eqv0-17bh-n8kn-9eonu7pl7u8y',
  },
  {
    id: 136,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 186,
      left: 710,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: '7ar5nvtv-54yc-wsr5-mrhy-d5am698xxsue',
  },
  {
    id: 137,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_137',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 138,
    polarity: {
      1: [139],
      2: [140],
    },
    direction: {
      left: '1',
      right: '2',
    },
    rotate: {
      left: -94,
      right: 270,
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 109,
      left: 892,
      width: 20,
      height: 20,
      rotate: 90,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: '4gdsee3m-3t6j-7eai-232n-n6509smopqrr',
  },
  {
    id: 138,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,100 0',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 120,
      left: 705,
      width: 29,
      color: '#3474E4',
    },
    key: 'n692luyg-xfsr-o5cl-7g20-t4qmulzdr24d',
  },
  {
    id: 139,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 -3,27 -3',
    arrow_transform: 'translate(27,-3) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 106,
      left: 902,
      width: 29,
      color: '#3474E4',
    },
    key: 'efli6byq-yty7-hex7-n23q-hs7g8zc8e3tm',
  },
  {
    id: 140,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 5,12 5,12 18,0 18',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 126,
      left: 902,
      width: 29,
      color: '#3474E4',
    },
    key: 'v9wul024-sptb-io3d-lfq5-ekq3wkntiwva',
  },
  {
    id: 141,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_141',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 144,
    polarity: {
      1: [145],
      2: [142, 140],
    },
    direction: {
      left: '1',
      right: '2',
    },
    rotate: {
      left: -97,
      right: 270,
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 154,
      left: 892,
      width: 20,
      height: 20,
      rotate: 90,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: 'r44el3j8-z5cp-jukd-gr63-85aobk33u7mj',
  },
  {
    id: 142,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 5,28 5',
    arrow_transform: 'translate(28, 5) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 175,
      left: 900,
      width: 29,
      color: '#3474E4',
    },
    key: 'g93as3ow-jlv9-qfar-mwif-oppf667obtuz',
  },
  {
    id: 143,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,85 0,85 42,125 42',
    arrow_transform: 'translate(125, 42) rotate(180)',
    // animateStartRight: true,
    no_circle: true,
    style: {
      top: 140,
      left: 705,
      width: 29,
      color: '#3474E4',
    },
    key: 'irls51kr-5y2v-fd9v-nl2i-1dqikdkrwf43',
  },
  {
    id: 144,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,75 0,75 -35,95 -35',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 235,
      left: 705,
      width: 29,
      color: '#3474E4',
    },
    key: 'j499e14e-nbp1-9ucy-f6aq-sby2okaqxaxu',
  },
  {
    id: 145,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 -5,28 -5',
    arrow_transform: 'translate(28, -5) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 155,
      left: 902,
      width: 29,
      color: '#3474E4',
    },
    key: 'uenza6bg-to2q-yf6j-upnb-49so1dv9scc2',
  },
  {
    id: 146,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,5 0',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 118,
      left: 910,
      width: 29,
      color: '#3474E4',
    },
    key: 'f615afhl-6aif-xsja-51jp-o3ih8l28evcz',
  },
  {
    id: 147,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 114,
      left: 920,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: 'myavsm45-96lr-z373-x2f3-nd5mscosqjgx',
  },
  {
    id: 148,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_148',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 150,
    polarity: {
      1: [149],
      2: [153],
    },
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 112,
      left: 1110,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: '7c4umikn-afd1-lmun-m5xl-33miiuwppefs',
  },
  {
    id: 149,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,10 0,10 5',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 100,
      left: 1099,
      width: 29,
      color: '#3474E4',
    },
    key: 'ap78et3f-eunm-syls-lvt9-0pxj5ppcjjo9',
  },
  {
    id: 150,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,62 0',
    arrow_transform: 'translate(62 0) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 122,
      left: 1130,
      width: 29,
      color: '#3474E4',
    },
    key: 'wtek904y-a4ht-o799-ivog-4z6gog1ddxr0',
  },
  {
    id: 151,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,10 0',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 121,
      left: 1099,
      width: 29,
      color: '#3474E4',
    },
    key: 'cpwdkcga-djtr-539q-15ms-apr4lxtg4gle',
  },
  {
    id: 152,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 118,
      left: 1075,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: '871ldrul-ktz7-ns1w-i7pm-k6hj819pbeal',
  },
  {
    id: 153,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 17,5 17',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 130,
      left: 1120,
      width: 29,
      color: '#3474E4',
    },
    key: 'jm8nnrkj-vjdk-e6qc-41mx-ahsjmkvyw614',
  },
  {
    id: 154,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_154',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 156,
    polarity: {
      1: [155],
      2: [157],
    },
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 155,
      left: 1130,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: '29t77lfw-i58b-qhyd-toqv-n3kdomfzy557',
  },
  {
    id: 155,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0,20 5',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 145,
      left: 1100,
      width: 29,
      color: '#3474E4',
    },
    key: 'v2m2bpxu-pi6b-ts1x-1gaj-hm47e2slo8lo',
  },
  {
    id: 156,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,53 0',
    arrow_transform: 'translate(53 0) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 165,
      left: 1151,
      width: 29,
      color: '#3474E4',
    },
    key: 'sbgqqk9y-e21c-uyf6-9y92-qgcywlf7gou2',
  },
  {
    id: 157,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0,20 -5',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 185,
      left: 1100,
      width: 29,
      color: '#3474E4',
    },
    key: '25l5sl9b-ni1u-edfp-eohs-0cj26swlnngs',
  },
  {
    id: 158,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_158',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 160,
    polarity: {
      1: [159],
      2: [161],
    },
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 236,
      left: 1130,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
    key: '4im24pxb-kd7q-5ks1-ggdc-svnt1gjjjsdm',
  },
  {
    id: 159,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0,20 5',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 225,
      left: 1099,
      width: 29,
      color: '#3474E4',
    },
    key: '4rlajefs-ldam-fi8x-n10b-bnxu30q3akoh',
  },
  {
    id: 160,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,56 0',
    arrow_transform: 'translate(56, 0) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 245,
      left: 1145,
      width: 29,
      color: '#3474E4',
    },
    key: '9zqoxbm6-o9qc-fsoo-mtrv-xy394903yd14',
  },
  {
    id: 161,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0,20 -5',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 264,
      left: 1099,
      width: 29,
      color: '#3474E4',
    },
    key: '1zfas134-w96o-dfuj-wgm9-3c915d4ur82m',
  },
  {
    id: 162,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,3 0',
    no_arrow: true,
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 245,
      left: 1122,
      width: 29,
      color: '#3474E4',
    },
    key: '4cnateoq-tfs5-2bfa-qpmm-u7yu54kilidv',
  },
  {
    id: 163,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 242,
      left: 1098,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
    key: 'pdgtkpar-kbdy-da6q-w3vl-ubu0ybljqqnv',
  },
  {
    id: 164,
    parent_id: 104,
    children_id: 176,
    type: 'equipment',
    equipment_name: '高速数传基带',
    device_key: 'DDT',
    equipment_icon: 'normal',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '载波锁定',
        value: 2,
        key: 'status',
      },
      {
        label: '码元锁定',
        value: 1,
        key: 'status',
      },
      {
        label: '码速率',
        value: '450M',
      },
      {
        label: '解调模式',
        value: 'BPSK',
      },
      {
        label: 'Eb/N0',
        value: '30.1dB',
      },
      {
        label: 'AGC',
        value: '30.1dB',
      },
    ],
    equipment_style: {
      width: '48%',
    },
    style: {
      top: 24,
      left: 1370,
      width: 270,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: 'ngoavrum-br5p-dfsh-nnkq-isbhl1225nrg',
  },
  {
    id: 165,
    type: 'equipment',
    equipment_name: '综合基带(测控)',
    device_key: 'BBE',
    parent_id: 96,
    children_id: [173, 180],
    equipment_icon: 'acu',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '工作方式',
        value: '待机',
      },
      {
        label: '天线位置',
        value: '123.123，123.123',
      },
      {
        label: '相位',
        value: '123，123',
      },
    ],
    style: {
      top: 204,
      left: 1369,
      width: 220,
      height: 154,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: 'oogovtf2-81gu-q2ix-ap1z-duh2vxbr2u83',
  },
  {
    id: 166,
    type: 'equipment',
    equipment_name: '跟踪接收机',
    device_key: 'TRK',
    parent_id: 94,
    children_id: 181,
    equipment_icon: 'track-machine',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '增益',
        value: '00db',
      },
      {
        label: '跟踪模式',
        value: '单载频',
      },
    ],
    style: {
      top: 391,
      left: 1374,
      width: 220,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: 'vk32otfx-j4aq-ohwt-h8p1-hb6dbzpcbw0a',
  },
  {
    id: 167,
    type: 'equipment',
    equipment_name: '跟踪接收机',
    device_key: 'TRK2',
    parent_id: 94,
    children_id: 182,
    equipment_icon: 'track-machine',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '增益',
        value: '00db',
      },
      {
        label: '跟踪模式',
        value: '单载频',
      },
    ],
    style: {
      top: 534,
      left: 1374,
      width: 220,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: '4s82fse8-yt8q-4px8-i06y-xlfmlelmzgyc',
  },
  {
    id: 168,
    type: 'equipment',
    parent_id: 105,
    children_id: [183, 178],
    equipment_name: '防火墙/交换机',
    equipment_icon: '',
    status: 'OFF_LINE',
    equipment_details: [],
    style: {
      top: 186,
      left: 1711,
      width: 118,
      height: 118,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
    key: 'hqnhfz9y-l34z-25ek-nchr-281u82tywk49',
  },
  {
    id: 169,
    type: 'equipment',
    parent_id: [106, 103],
    children_id: 177,
    equipment_name: '存储转发',
    equipment_icon: '',
    status: 'OFF_LINE',
    equipment_details: [],
    style: {
      top: 30,
      left: 1711,
      width: 118,
      height: 118,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: 'wf2aiwge-wsgp-ny6d-jfwf-1p3eax8puixd',
  },
  {
    id: 170,
    type: 'equipment',
    equipment_name: 'DTE',
    device_key: 'DTE',
    parent_id: [101, 102],
    children_id: 105,
    equipment_icon: 'dte',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '设备情况',
        value: '正常',
      },
      {
        label: '控制方式',
        value: '本控',
      },
      {
        label: '工作方式',
        value: '待机',
      },
    ],
    style: {
      top: 345,
      left: 1698,
      width: 144,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: 'vuesh5lr-o0z3-ge64-x4vx-1ie7qy6bk12p',
  },
  {
    id: 171,
    type: 'equipment',
    equipment_name: '天线控制',
    device_key: 'ACU',
    parent_id: 127,
    children_id: 96,
    equipment_icon: 'acu',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '工作方式',
        value: '待机',
      },
      {
        label: '天线位置',
        value: '123.123，123.123',
      },
      {
        label: '相位',
        value: '123，123',
      },
    ],
    style: {
      top: 505,
      left: 1698,
      width: 144,
      height: 153,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
    key: 'skvgxd7r-goh2-almx-w76e-qz1hhqvoimt4',
  },
  {
    id: 172,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,33 0',
    arrow_transform: 'translate(33, 0) rotate(180)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 86,
      left: 1303,
      width: 29,
      color: '#3474E4',
    },
    key: '5vfn8842-vjuq-ojus-21ce-hvqcwitf4q6x',
  },
  {
    id: 173,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,33 0',
    arrow_transform: 'translate(33, 0) rotate(180)',
    animateStartRight: true,
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 282,
      left: 1302,
      width: 29,
      color: '#3474E4',
    },
    key: '74wqzgf3-799v-c4wv-vmdb-6zudgo4fnr6s',
  },
  {
    id: 174,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,33 0',
    arrow_transform: 'translate(33, 0) rotate(180)',
    no_circle: true,
    style: {
      top: 453,
      left: 1303,
      width: 29,
      color: '#3474E4',
    },
    key: '3cysdf1x-zu1o-7xdt-amgx-iajxctl5kups',
  },
  {
    id: 175,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,33 0',
    arrow_transform: 'translate(33, 0) rotate(180)',
    no_circle: true,
    style: {
      top: 597,
      left: 1303,
      width: 29,
      color: '#3474E4',
    },
    key: '97ql2os5-j0id-qs4i-k69q-ihbkuq4rbwto',
  },
  {
    id: 176,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,35 0',
    arrow_transform: 'translate(35, 0) rotate(180)',
    animateStartRight: true,
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 87,
      left: 1640,
      width: 29,
      color: '#3474E4',
    },
    key: '8t4ealpq-brwa-46ub-wf9m-ojez5bknp35j',
  },
  {
    id: 177,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 18',
    arrow_transform: 'translate(0, 18) rotate(-90)',
    animateStartRight: true,
    no_circle: true,
    style: {
      top: 148,
      left: 1770,
      width: 29,
      color: '#3474E4',
    },
    key: '7uf4hen6-0er8-9kww-gmk4-fuh9wlx1erzp',
  },
  {
    id: 178,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 18',
    arrow_transform: 'translate(0, 18) rotate(-90)',
    animateStartRight: true,
    line_start: 'arrow',
    line_start_arrow_transform: 'translate(0, 0) rotate(90)',
    no_circle: true,
    style: {
      top: 304,
      left: 1770,
      width: 29,
      color: '#3474E4',
    },
    key: '66o87u9d-kxdl-a2p8-ppg6-1a5368r4mqt9',
  },
  {
    id: 179,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,0 18',
    no_arrow: true,
    animateStartRight: true,
    line_start: 'arrow',
    line_start_arrow_transform: 'translate(0, 0) rotate(90)',
    no_circle: true,
    style: {
      top: 469,
      left: 1770,
      width: 29,
      color: '#3474E4',
    },
    key: 'wsgrygny-br79-jhm5-svj7-6l2gujr7zpu6',
  },
  {
    id: 180,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0,20 60,55 60',
    animateStartRight: true,
    line_start: 'arrow',
    arrow_transform: 'translate(55, 60) rotate(180)',
    no_circle: true,
    style: {
      top: 281,
      left: 1590,
      width: 29,
      color: '#3474E4',
    },
    key: 'y293kqm5-w6tw-ni74-h1s0-er95209peb5a',
  },
  {
    id: 181,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0,20 60,50 60',
    animateStartRight: true,
    line_start: 'arrow',
    arrow_transform: 'translate(50, 60) rotate(180)',
    no_circle: true,
    style: {
      top: 446,
      left: 1595,
      width: 29,
      color: '#3474E4',
    },
    key: 'ece2g6o7-riuh-7gjq-d6dj-y28ikq8y8rxu',
  },
  {
    id: 182,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,50 0',
    animateStartRight: true,
    line_start: 'arrow',
    arrow_transform: 'translate(50, 0) rotate(180)',
    no_circle: true,
    style: {
      top: 589,
      left: 1595,
      width: 29,
      color: '#3474E4',
    },
    key: 'ysgeywpi-a7hc-b4bt-cajv-nrtxixa38665',
  },
  {
    id: 183,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,20 0',
    animateStartRight: true,
    line_start: 'arrow',
    arrow_transform: 'translate(20, 0) rotate(180)',
    no_circle: true,
    style: {
      top: 238,
      left: 1829,
      width: 29,
      color: '#3474E4',
    },
    key: 'vvnhs7t5-jbx5-kr4u-koxg-ohst32adf8ke',
  },
];
export const topologyData = {
  polarity_device: ['ACU', 'CPB'],
  always_online: [47, 48, 49, 50, 51, 59, 60, 61, 80, 81, 82, 83, 84, 85, 86, 115, 116, 117, 118, 119, 120, 121, 105, 106, 169, 168],
  matrix: {
    '70M': 104,
  },
  // always_online: [22, 23, 24, 25, 29, 38, 63, 64, 65, 66, 78, 79, 80, 81, 98, 99, 100],
  element: topologyElement,
};
export function test() {
  // topologyElement.forEach((item, index) => ((item.key = randomWord(32)), delete item.order_id, (item.id = index + 1)));
  // topologyElement.forEach((item, index) => (item.style.left += 10));
  // console.log(topologyElement);
}
