//勐腊站拓扑图

const topologyElement = [
  // {
  //   device_key: 'CPB',
  //   deviceId: '',
  //   deviceStatus: 'OFF_LINE',
  //   name: '信道插箱',
  // },
  {
    device_key: 'IF_MATRIX',
    deviceId: '',
    deviceStatus: 'OFF_LINE',
    name: '中频矩阵',
  },
  {
    id: 1,
    status: 'OFF_LINE',
    type: 'round_rect',
    text: 'X频段馈源',
    style: {
      width: 47,
      height: 310,
      top: 10,
      left: 219,
      color: '#167AFF',
      background: 'var(--yx-background-3)',
      border: '2px solid #FFFFFF',
      borderRadius: [20],
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '35px',
    },
  },
  {
    id: 2,
    status: 'OFF_LINE',
    type: 'round_rect',
    text: 'S频段馈源',
    style: {
      width: 47,
      height: 310,
      top: 340,
      left: 219,
      background: 'var(--yx-background-3)',
      border: '2px solid #FFFFFF',
      color: '#07D0D0',
      borderRadius: [20],
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '35px',
    },
  },
  {
    id: 3,
    type: 'arrow',
    children_id: 9,
    status: 'OFF_LINE',
    parent_id: 1,
    style: {
      top: 30,
      left: 266,
      width: 10,
      color: 'var(--yx-font-4)',
    },
  },
  {
    id: 4,
    children_id: 10,
    status: 'OFF_LINE',
    parent_id: 1,
    type: 'arrow',
    style: {
      top: 73,
      left: 266,
      width: 10,
      color: '#C3C9D2',
      transform: '',
    },
  },
  {
    id: 5,
    type: 'arrow',
    status: 'OFF_LINE',
    children_id: 11,
    parent_id: 1,
    style: {
      top: 156,
      left: 264,
      width: 10,
      color: '#3474E4',
      transform: 'translate(11,0) rotate(180)',
    },
  },
  {
    id: 6,
    type: 'arrow',
    children_id: 12,
    status: 'OFF_LINE',
    parent_id: 1,
    style: {
      top: 206,
      left: 264,
      width: 10,
      color: '#C3C9D2',
      transform: 'translate(11,0) rotate(180)',
    },
  },
  {
    id: 7,
    type: 'arrow',
    children_id: 13,
    status: 'OFF_LINE',
    parent_id: 1,
    style: {
      top: 256,
      left: 264,
      width: 10,
      color: '#3474E4',
      transform: 'translate(11,0) rotate(180)',
    },
  },
  {
    id: 8,
    type: 'arrow',
    children_id: 14,
    status: 'OFF_LINE',
    parent_id: 1,
    style: {
      top: 303,
      left: 264,
      width: 10,
      color: '#C3C9D2',
      transform: 'translate(11,0) rotate(180)',
    },
  },
  {
    id: 9,
    type: 'round_rect_mini',
    text: 'LHPC',
    children_id: 67,
    status: 'OFF_LINE',
    parent_id: 3,
    style: {
      top: 18,
      left: 286,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 10,
    type: 'round_rect_mini',
    children_id: 68,
    status: 'OFF_LINE',
    parent_id: 4,
    text: 'RHPC',
    style: {
      top: 62,
      left: 286,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      background: '#F1F4F7',
      border: '1px solid #FFFFFF',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 11,
    type: 'round_rect_mini',
    text: 'LHPC',
    children_id: 17,
    status: 'OFF_LINE',
    parent_id: 5,
    style: {
      top: 144,
      left: 286,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 12,
    type: 'round_rect_mini',
    status: 'OFF_LINE',
    text: 'RHPC',
    children_id: 18,
    parent_id: 6,
    style: {
      top: 196,
      left: 286,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 13,
    type: 'round_rect_mini',
    status: 'OFF_LINE',
    children_id: 19,
    parent_id: 7,
    text: 'LHPC',
    style: {
      top: 244,
      left: 286,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 14,
    type: 'round_rect_mini',
    text: 'RHPC',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 291,
      left: 286,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 15,
    type: 'rect-mini',
    status: 'OFF_LINE',
    children_id: 20,
    parent_id: 8,
    style: {
      top: 46,
      left: 343,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #fff',
      borderRadius: [2],
    },
  },
  {
    id: 16,
    type: 'ball-mini',
    status: 'OFF_LINE',
    paramKey: 'ACU_JX_X_3',
    paramValue: 'ACU_JX_X_3_SET',
    line_color: '#C3C9D2',
    active_color: 'rgb(52, 116, 228)',
    parent_id: [67, 68],
    children_id: 135,
    polarity: { 1: [67, 9, 3], 2: [68, 10, 4] }, //极化方向矩形
    direction: {
      left: '1',
      right: '2',
    },
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 40,
      left: 390,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
  },
  {
    id: 17,
    type: 'line-straight',
    status: 'OFF_LINE',
    children_id: 22,
    parent_id: 11,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    style: {
      top: 156,
      left: 358,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 18,
    type: 'line-straight',
    status: 'OFF_LINE',
    children_id: 23,
    parent_id: 12,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    style: {
      top: 206,
      left: 358,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 19,
    type: 'line-straight',
    status: 'OFF_LINE',
    line_points: '0 0, 29 0',
    children_id: 24,
    parent_id: 13,
    arrow_transform: 'translate(29 0) rotate(180)',
    style: {
      top: 256,
      left: 358,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 20,
    type: 'line-straight',
    status: 'OFF_LINE',
    line_points: '0 0, 29 0',
    children_id: 25,
    parent_id: 14,
    arrow_transform: 'translate(29 0) rotate(180)',
    style: {
      top: 302,
      left: 358,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 21,
    type: 'equipment',
    status: 'OFF_LINE',
    children_id: 16,
    parent_id: 27,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'X-BUC',
    device_key: 'X_BUC',
    equipment_icon: 'buc',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '增益',
        value: '00db',
      },
      {
        label: '输出功率',
        value: '00dBm',
      },
    ],
    style: {
      top: 10,
      left: 418,
      width: 170,
      height: 114,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 22,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 17,
    children_id: 28,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '和场放1',
    equipment_icon: 'add-play',
    status: 'null',
    equipment_details: [],
    style: {
      top: 139,
      left: 418,
      width: 123,
      height: 33,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 23,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 18,
    children_id: 39,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '和场放2',
    equipment_icon: 'add-play',
    status: null,
    equipment_details: [],
    style: {
      top: 191,
      left: 418,
      width: 123,
      height: 33,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 24,
    type: 'equipment',
    line_points: '0 0, 29 0',
    parent_id: 19,
    children_id: 45,
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '差场放1',
    equipment_icon: 'bad-play',
    status: null,
    equipment_details: [],
    style: {
      top: 239,
      left: 418,
      width: 123,
      height: 33,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 25,
    type: 'equipment',
    parent_id: 20,
    children_id: 46,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '差场放2',
    equipment_icon: 'bad-play',
    status: null,
    equipment_details: [],
    style: {
      top: 286,
      left: 418,
      width: 123,
      height: 33,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 26,
    type: 'round_rect',
    parent_id: [27, 32, 49, 50, 48, 82, 92, 93],
    children_id: [94, 95, 27, 126],
    status: 'OFF_LINE',
    text: '70M矩阵',
    style: {
      width: 47,
      height: 458,
      top: 10,
      left: 1226,
      color: '#167AFF',
      background: 'rgba(255,255,255,0.12)',
      border: '2px solid #2680EB',
      borderRadius: [20],
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '35px',
      wordBreak: 'break-all',
    },
  },
  {
    id: 27,
    status: 'OFF_LINE',
    type: 'line-straight',
    line_points: '0 0, 80 0 ,80 -17, 318 -17',
    parent_id: 21,
    children_id: 26,
    animateStartRight: true,
    arrow_transform: '',
    line_circle: {
      cx: 318,
      cy: -17,
    },
    style: {
      top: 57,
      left: 589,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 28,
    type: 'line-straight',
    parent_id: 22,
    status: 'OFF_LINE',
    children_id: 29,
    line_points: '0 0, 26 0, 26 -15, 36 -15',
    arrow_transform: 'translate(36 -15) rotate(180)',
    style: {
      top: 155,
      left: 541,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 29,
    type: 'rect-mini',
    text: '功分器',
    parent_id: 28,
    status: 'OFF_LINE',
    equipment_name: '功分器1',
    children_id: [30, 42, 117],
    style: {
      top: 83,
      left: 614,
      width: 34,
      height: 78,
      color: '#4B4F55',
      background: '#FFFFFF',
      borderRadius: [2],
      fontSize: '14px',
    },
  },
  {
    id: 30,
    type: 'line-straight',
    parent_id: 29,
    status: 'OFF_LINE',
    children_id: 31,
    line_points: '0 0, 20 0, 20 -10,45 -10,45 0',
    no_arrow: true,
    // arrow_transform: 'translate(45 0) rotate(180)',
    style: {
      top: 95,
      left: 649,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 31,
    type: 'equipment',
    equipment_name: 'X下变频器1',
    device_key: 'XDC1',
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    parent_id: 30,
    children_id: [32, 54],
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '增益',
        value: '00db',
      },
    ],
    style: {
      top: 38,
      left: 918,
      width: 170,
      height: 94,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px',
      fontSize: '14px',
    },
  },
  {
    id: 32,
    type: 'line-straight',
    parent_id: 31,
    status: 'OFF_LINE',
    children_id: 26,
    line_points: '0 0, 68 0',
    arrow_transform: 'translate(68 0) rotate(180)',
    style: {
      top: 85,
      left: 1089,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 33,
    type: 'equipment',
    equipment_name: '跟踪接收机',
    device_key: 'TRK',
    parent_id: 94,
    children_id: 127,
    equipment_icon: 'track-machine',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '增益',
        value: '00db',
      },
      {
        label: '跟踪模式',
        value: '单载频',
      },
    ],
    style: {
      top: 20,
      left: 1338,
      width: 220,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 34,
    type: 'equipment',
    equipment_name: '天线控制',
    device_key: 'ACU',
    parent_id: 127,
    children_id: 96,
    equipment_icon: 'acu',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '工作方式',
        value: '待机',
      },
      {
        label: '天线位置',
        value: '123.123，123.123',
      },
      {
        label: '相位',
        value: '123，123',
      },
    ],
    style: {
      top: 35,
      left: 1631,
      width: 220,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 35,
    type: 'equipment',
    equipment_name: '综合基带(中低速)',
    device_key: 'BBE2',
    parent_id: 95,
    children_id: 102,
    equipment_icon: 'normal',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '工作方式',
        value: '标准',
      },
      {
        label: '上行频率',
        value: '1234.1234MHz',
      },
      {
        label: '下行频率',
        value: '1234.1234MHz',
      },
      {
        label: '监控模式',
        value: '低速数传',
      },
    ],
    style: {
      top: 324,
      left: 1338,
      width: 220,
      height: 154,
      // color: '#61666A',
      // boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      // background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 36,
    type: 'equipment',
    equipment_name: 'X下变频器2',
    device_key: 'XDC2',
    parent_id: 40,
    children_id: [53],
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '增益',
        value: '00db',
      },
    ],
    style: {
      top: 138,
      left: 918,
      width: 170,
      height: 94,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px',
      fontSize: '14px',
    },
  },
  {
    id: 37,
    type: 'equipment',
    equipment_name: 'X下变频器3',
    device_key: 'XDC3',
    parent_id: 42,
    children_id: [52],
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '增益',
        value: '00db',
      },
    ],
    style: {
      top: 238,
      left: 918,
      width: 170,
      height: 94,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '10px 5px',
      fontSize: '14px',
    },
  },

  {
    id: 38,
    type: 'rect-mini',
    text: '功分器',
    parent_id: 39,
    status: 'OFF_LINE',
    equipment_name: '功分器2',
    children_id: [40, 43, 118],
    style: {
      top: 168,
      left: 614,
      width: 34,
      height: 78,
      color: '#4B4F55',
      background: '#FFFFFF',
      borderRadius: [2],
      fontSize: '14px',
    },
  },
  {
    id: 39,
    type: 'line-straight',
    line_points: '0 0, 36 0',
    parent_id: 23,
    children_id: 38,
    status: 'OFF_LINE',
    arrow_transform: 'translate(36 0) rotate(180)',
    style: {
      top: 207,
      left: 541,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 40,
    type: 'line-straight',
    line_points: '0 0, 105 0,105 40,133 40',
    parent_id: 38,
    children_id: 36,
    status: 'OFF_LINE',
    arrow_transform: 'translate(133 40) rotate(180)',
    style: {
      top: 205,
      left: 649,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 41,
    type: 'equipment',
    equipment_name: 'X合成网络',
    device_key: 'X_CIN',
    parent_id: [44, 47],
    children_id: 48,
    equipment_icon: 'comprise-network',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '旋向',
        value: '左旋',
      },
      {
        label: '增益',
        value: '00db',
      },
    ],
    style: {
      top: 262,
      left: 677,
      width: 170,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 12px',
      fontSize: '14px',
    },
  },
  {
    id: 42,
    type: 'line-straight',
    parent_id: 29,
    children_id: 44,
    status: 'OFF_LINE',
    line_points: '0 0, 51 0 ,51 40',
    no_arrow: true,
    style: {
      top: 142,
      left: 649,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 43,
    type: 'line-straight',
    parent_id: 38,
    children_id: 41,
    status: 'OFF_LINE',
    line_points: '0 0, 50 0, 50 -8',
    arrow_transform: 'translate(51 28) rotate(-90)',
    no_arrow: true,
    active_color: '#C3C9D2',
    style: {
      top: 235,
      left: 649,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 44,
    type: 'ball-mini',
    paramKey: 'CPB_JX_6',
    paramValue: 'CPB_JX_6_SET',
    parent_id: [42, 43],
    status: 'OFF_LINE',
    polarity: { '01': [42, 17, 11, 5], 10: [43, 12, 6, 18] },
    direction: {
      left: '01',
      right: '10',
    },
    children_id: 133,
    active_color: 'rgb(52, 116, 228)',
    line_color: '#C3C9D2',
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 213,
      left: 741,
      width: 20,
      height: 20,
      color: '#A2B2C5',
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      transform: 'scale(2.008) translate(0, 0.5)',
      borderRadius: [2],
    },
  },
  {
    id: 45,
    type: 'line-straight',
    parent_id: 24,
    children_id: 47,
    status: 'OFF_LINE',
    line_points: '0 0, 42 0,42 13.5',
    no_arrow: true,
    style: {
      top: 256,
      left: 541,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 46,
    type: 'line-straight',
    parent_id: 25,
    children_id: 47,
    status: 'OFF_LINE',
    line_points: '0 0, 41.5 0, 41.5 -10',
    no_arrow: 1,
    arrow_transform: 'translate(41 -8) rotate(90)',
    style: {
      top: 302,
      left: 541,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 47,
    type: 'ball-mini',
    paramKey: 'ACU_JX_X_2',
    paramValue: 'ACU_JX_X_2_SET',
    parent_id: [45, 46],
    polarity: { 1: [45, 19, 13, 7], 2: [46, 20, 14, 8] },
    direction: {
      left: '1',
      right: '2',
    },
    children_id: 137,
    status: 'OFF_LINE',
    active_color: 'rgb(52, 116, 228)',
    line_color: '#C3C9D2',
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 273,
      left: 615,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
      zIndex: 2,
    },
  },
  {
    id: 48,
    type: 'line-straight',
    parent_id: 41,
    children_id: 26,
    status: 'OFF_LINE',
    line_points: '0 0, 189 0 ',
    arrow_transform: 'translate(189 0) rotate(180)',
    style: {
      top: 340,
      left: 847,
      width: 29,
      color: '#3474E4',
    },
  },
  // {
  //   id: 49,
  //   type: 'line-straight',
  //   parent_id: 36,
  //   children_id: 26,
  //   status: 'OFF_LINE',
  //   line_points: '0 0, 69 0 ',
  //   arrow_transform: 'translate(69 0) rotate(180)',
  //   style: {
  //     top: 175,
  //     left: 1088,
  //     width: 29,
  //     color: '#3474E4',
  //   },
  // },
  // {
  //   id: 50,
  //   type: 'line-straight',
  //   parent_id: 37,
  //   children_id: 26,
  //   status: 'OFF_LINE',
  //   line_points: '0 0, 69 0 ',
  //   arrow_transform: 'translate(69 0) rotate(180)',
  //   style: {
  //     top: 275,
  //     left: 1088,
  //     width: 29,
  //     color: '#3474E4',
  //   },
  // },
  {
    id: 51,
    type: 'round_rect',
    text: '1.2G矩阵',
    parent_id: [52, 53, 54],
    status: 'OFF_LINE',
    children_id: 104,
    style: {
      width: 47,
      height: 172,
      top: 479,
      left: 1226,
      color: '#334681',
      background: 'rgba(255,255,255,0.12)',
      border: '2px solid #fff',
      borderRadius: [20],
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '25px',
      wordBreak: 'break-all',
    },
  },
  {
    id: 52,
    type: 'line-straight',
    parent_id: 37,
    status: 'OFF_LINE',
    children_id: 51,
    line_points: '0 0, 50 0, 50 150,69 150',
    arrow_transform: 'translate(69 150) rotate(180)',
    style: {
      top: 290,
      left: 1088,
      width: 29,
      color: '#fff',
    },
  },
  {
    id: 53,
    type: 'line-straight',
    parent_id: 36,
    children_id: 51,
    status: 'OFF_LINE',
    line_points: '0 0, 55 0, 55 170,69 170',
    arrow_transform: 'translate(69 170) rotate(180)',
    style: {
      top: 190,
      left: 1088,
      width: 29,
      color: '#fff',
    },
  },
  {
    id: 54,
    type: 'line-straight',
    parent_id: 31,
    children_id: 51,
    status: 'OFF_LINE',
    line_points: '0 0, 60 0, 60 200,69 200',
    arrow_transform: 'translate(69 200) rotate(180)',
    style: {
      top: 100,
      left: 1088,
      width: 29,
      color: '#fff',
    },
  },
  {
    id: 55,
    type: 'arrow',
    parent_id: 2,
    status: 'OFF_LINE',
    children_id: 61,
    s_fed: true,
    style: {
      top: 360,
      left: 266,
      width: 10,
      color: '#3474E4',
    },
  },
  {
    id: 56,
    type: 'arrow',
    s_fed: true,
    parent_id: 2,
    status: 'OFF_LINE',
    children_id: 62,
    style: {
      top: 403,
      left: 266,
      width: 10,
      color: '#C3C9D2',
      transform: '',
    },
  },
  {
    id: 57,
    type: 'arrow',
    parent_id: 2,
    children_id: 63,
    status: 'NORMAL',
    s_fed: true,
    style: {
      top: 486,
      left: 264,
      width: 10,
      color: '#3474E4',
      transform: 'translate(11,0) rotate(180)',
    },
  },
  {
    id: 58,
    type: 'arrow',
    parent_id: 2,
    children_id: 64,
    status: 'NORMAL',
    s_fed: true,
    style: {
      top: 530,
      left: 264,
      width: 10,
      color: '#C3C9D2',
      transform: 'translate(11,0) rotate(180)',
    },
  },
  {
    id: 59,
    type: 'arrow',
    parent_id: 2,
    children_id: 65,
    status: 'NORMAL',
    s_fed: true,
    style: {
      top: 574,
      left: 264,
      width: 10,
      color: '#3474E4',
      transform: 'translate(11,0) rotate(180)',
    },
  },
  {
    id: 60,
    type: 'arrow',
    parent_id: 2,
    status: 'NORMAL',
    s_fed: true,
    children_id: 66,
    style: {
      top: 618,
      left: 264,
      width: 10,
      color: '#C3C9D2',
      transform: 'translate(11,0) rotate(180)',
    },
  },
  {
    id: 61,
    type: 'round_rect_mini',
    parent_id: 55,
    status: 'OFF_LINE',
    children_id: 75,
    text: 'LHPC',
    s_fed: true,
    style: {
      top: 348,
      left: 286,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 62,
    status: 'OFF_LINE',
    type: 'round_rect_mini',
    parent_id: 56,
    children_id: 76,
    text: 'RHPC',
    s_fed: true,
    style: {
      top: 392,
      left: 286,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 63,
    type: 'round_rect_mini',
    status: 'OFF_LINE',
    parent_id: 57,
    children_id: 71,
    text: 'LHPC',
    s_fed: true,
    style: {
      top: 474,
      left: 286,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 64,
    type: 'round_rect_mini',
    parent_id: 58,
    s_fed: true,
    status: 'OFF_LINE',
    children_id: 72,
    text: 'RHPC',
    style: {
      top: 520,
      left: 286,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 65,
    type: 'round_rect_mini',
    parent_id: 59,
    s_fed: true,
    status: 'OFF_LINE',
    children_id: 73,
    text: 'LHPC',
    style: {
      top: 562,
      left: 286,
      width: 72,
      height: 24,
      color: '#fff',
      border: '1px solid #FFFFFF',
      background: 'linear-gradient(90deg, #0069FF 0%, rgba(0,105,255,0) 100%)',
      borderRadius: [12],
      fontSize: '16px',
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 66,
    type: 'round_rect_mini',
    parent_id: 60,
    s_fed: true,
    status: 'OFF_LINE',
    children_id: 74,
    text: 'RHPC',
    style: {
      top: 606,
      left: 286,
      width: 72,
      height: 24,
      color: '#C3C9D2',
      border: '1px solid #FFFFFF',
      background: '#F1F4F7',
      borderRadius: [20],
      textAlign: 'center',
      lineHeight: '24px',
    },
  },
  {
    id: 67,
    type: 'line-straight',
    parent_id: 9,
    status: 'OFF_LINE',
    children_id: 16,
    text: 'RHPC',
    line_points: '0 0,21 0, 21 10',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    line_circle: {
      cx: 30,
      cy: 9.5,
    },
    style: {
      top: 30,
      left: 358,
      width: 20,
      height: 24,
      color: '#3474E4',
    },
  },
  {
    id: 68,
    parent_id: 10,
    status: 'OFF_LINE',
    children_id: 16,
    type: 'line-straight',
    text: 'RHPC',
    line_points: '0 0,21 0,21 -12',
    arrow_transform: 'translate(0 0) rotate(0)',
    animateStartRight: true,
    no_circle: false,
    line_circle: {
      cx: 30,
      cy: -12,
    },
    style: {
      top: 73,
      left: 358,
      width: 22,
      height: 24,
      color: '#C3C9D2',
    },
  },
  {
    id: 69,
    type: 'rect-mini',
    parent_id: null,
    status: 'OFF_LINE',
    children_id: 70,
    style: {
      top: 376,
      left: 343,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #C3C9D2',
      borderRadius: [2],
    },
  },
  {
    id: 70,
    type: 'ball-mini',
    paramKey: 'ACU_JX_S_3',
    paramValue: 'ACU_JX_S_3_SET',
    s_fed: true,
    polarity: { 0: [75, 61, 55], 1: [76, 62, 56] },
    direction: {
      left: '0',
      right: '1',
    },
    parent_id: [75, 76],
    status: 'OFF_LINE',
    children_id: 138,
    active_color: 'rgb(52, 116, 228)',
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 370,
      left: 390,
      width: 20,
      height: 20,
      color: '#A2B2C5',
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
  },
  {
    id: 71,
    type: 'line-straight',
    status: 'NORMAL',
    parent_id: 63,
    children_id: 78,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    style: {
      top: 486,
      left: 358,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 72,
    type: 'line-straight',
    parent_id: 64,
    status: 'NORMAL',
    children_id: 79,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    style: {
      top: 530,
      left: 358,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 73,
    type: 'line-straight',
    parent_id: 65,
    status: 'NORMAL',
    children_id: 80,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    style: {
      top: 574,
      left: 358,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 74,
    parent_id: 66,
    status: 'NORMAL',
    children_id: 81,
    type: 'line-straight',
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    style: {
      top: 618,
      left: 358,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 75,
    parent_id: 61,
    status: 'OFF_LINE',
    children_id: 70,
    s_fed: true,
    type: 'line-straight',
    line_points: '0 0,21 0, 21 10',
    animateStartRight: true,
    line_circle: {
      cx: 30,
      cy: 10,
    },
    style: {
      top: 360,
      left: 358,
      width: 21,
      height: 24,
      color: '#3474E4',
    },
  },
  {
    id: 76,
    type: 'line-straight',
    parent_id: 62,
    status: 'OFF_LINE',
    children_id: 70,
    line_points: '0 0,21 0, 21 -11.5',
    animateStartRight: true,
    s_fed: true,
    no_circle: false,
    line_circle: {
      cx: 30,
      cy: -12,
    },
    style: {
      top: 403,
      left: 358,
      width: 21,
      height: 24,
      color: '#C3C9D2',
    },
  },
  {
    id: 77,
    type: 'equipment',
    parent_id: 70,
    status: 'OFF_LINE',
    children_id: 82,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: 'S-BUC',
    device_key: 'S_BUC',
    equipment_icon: 'buc',
    s_fed: true, //S频段馈源
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '增益',
        value: '00db',
      },
      {
        label: '输出功率',
        value: '00dBm',
      },
    ],
    style: {
      top: 335,
      left: 418,
      width: 170,
      height: 114,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
      zIndex: -1,
    },
  },
  {
    id: 78,
    type: 'equipment',
    parent_id: 71,
    s_fed: true,
    children_id: [85, 121],
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '和场放1',
    equipment_icon: 'add-play',
    status: null,
    equipment_details: [],
    style: {
      top: 469,
      left: 418,
      width: 123,
      height: 33,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 79,
    type: 'equipment',
    parent_id: 72,
    s_fed: true,
    children_id: [86, 122],
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '和场放2',
    equipment_icon: 'add-play',
    status: null,
    equipment_details: [],
    style: {
      top: 515,
      left: 418,
      width: 123,
      height: 33,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 80,
    type: 'equipment',
    parent_id: 73,
    children_id: 88,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '差场放1',
    s_fed: true,
    equipment_icon: 'bad-play',
    status: null,
    equipment_details: [],
    style: {
      top: 558,
      left: 418,
      width: 123,
      height: 33,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 81,
    type: 'equipment',
    parent_id: 74,
    children_id: 89,
    line_points: '0 0, 29 0',
    arrow_transform: 'translate(29 0) rotate(180)',
    equipment_name: '差场放2',
    s_fed: true,
    equipment_icon: 'bad-play',
    status: null,
    equipment_details: [],
    style: {
      top: 602,
      left: 418,
      width: 123,
      height: 33,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: 'var(--yx-background-3)',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 82,
    type: 'line-straight',
    parent_id: 77,
    children_id: 26,
    line_points: '0 0, 146 0 ,146 -20,318 -20',
    status: 'OFF_LINE',
    arrow_transform: '',
    animateStartRight: true,
    style: {
      top: 392,
      left: 588,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 83,
    type: 'equipment',
    equipment_name: 'S合成网络',
    device_key: 'S_CIN2',
    parent_id: 91,
    children_id: 93,
    equipment_icon: 'comprise-network',
    status: 'OFF_LINE',
    s_fed: true,
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '旋向',
        value: '左旋',
      },
      {
        label: '增益',
        value: '00db',
      },
    ],
    style: {
      top: 548,
      left: 677,
      width: 170,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 84,
    type: 'equipment',
    parent_id: 87,
    children_id: 92,
    equipment_name: 'S下变频器1',
    device_key: 'SDC1',
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    s_fed: true,
    equipment_details: [
      {
        label: '衰减',
        value: '30db',
      },
      {
        label: '效率',
        value: '12345.1234Hz',
      },
    ],
    style: {
      top: 380,
      left: 918,
      width: 170,
      height: 119,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '10px',
      fontSize: '14px',
    },
  },
  {
    id: 85,
    type: 'line-straight',
    parent_id: 78,
    children_id: 87,
    status: 'OFF_LINE',
    line_points: '0 0, 67 0',
    arrow_transform: 'translate(67 0) rotate(180)',
    style: {
      top: 486,
      left: 541,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 86,
    type: 'line-straight',
    parent_id: 79,
    children_id: 87,
    status: 'OFF_LINE',
    line_points: 'M 0 0 17 0 A 20 50 0 0 1 29 0 L 170 0 170 10 186 10', // 170 0,170 10,186 10',
    isArc: true, //是否显示为弧段
    // no_arrow: 1,
    arrow_transform: 'translate(186 10) rotate(180)',
    // line_points: 'M 0 0, L 160 0, 160 -110, 165 -110 A 20 50 0 0 0 175 -110 L 189 -110',
    //M 0 0 L 200 0  A 20 50 0 0 1 220 0 L 400 0  A 20 弧线x轴半径，50弧线Y轴半径,第三个参数是角度,第四个参数0是短边1是长边，第五个参数是否是顺时针0逆时针1顺时针
    //第六个参数终点X坐标 Y坐标  //控制弧线向上还是向下用顺时针参数控制
    style: {
      top: 539,
      left: 541,
      width: 29,
      color: '#3474E4',
      // zIndex: 1,
    },
  },
  {
    id: 87,
    type: 'ball-mini',
    paramKey: 'CPB_JX_5',
    paramValue: 'CPB_JX_5_SET',
    parent_id: [30, 118],
    polarity: { '01': [30, 17, 11, 5], 10: [118, 18, 12, 6] },
    direction: {
      left: '01',
      right: '10',
    },
    children_id: 131,
    status: 'OFF_LINE',
    active_color: 'rgb(52, 116, 228)',
    circle_cx: 5,
    circle_cy: 5,
    style: {
      top: 85,
      left: 730,
      width: 20,
      height: 20,
      transition: 'all 0.5s ease 0s',
      zIndex: 2,
      color: '#A2B2C5',
      transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
      borderRadius: [2],
    },
  },
  {
    id: 88,
    type: 'line-straight',
    parent_id: 80,
    children_id: 90,
    status: 'OFF_LINE',
    line_points: '0 0, 23 0,23 -35,67 -35',
    arrow_transform: 'translate(67 -35) rotate(180)',
    style: {
      top: 574,
      left: 541,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 89,
    type: 'line-straight',
    parent_id: 81,
    status: 'OFF_LINE',
    children_id: 90,
    line_points: '0 0, 68 0',
    arrow_transform: 'translate(68 0) rotate(180)',
    style: {
      top: 618,
      left: 541,
      width: 29,
      color: '#3474E4',
    },
  },
  // {
  //   id: 90,
  //   type: 'ball-mini',
  //   paramKey: 'JX_4',
  //   parent_id: [88, 89],
  //   polarity: { [LEFT_HANDED]: 65, [RIGHT_HANDED]: 66 },
  //   status: 'OFF_LINE',
  //   children_id: 83,
  //   active_color: 'rgb(52, 116, 228)',
  //   direction: 'L',
  //   circle_cx: 5,
  //   circle_cy: 5,
  //   style: {
  //     top: 586,
  //     left: 577,
  //     width: 20,
  //     height: 20,
  //     color: '#A2B2C5',
  //     transition: 'all 0.5s ease 0s',
  //     zIndex: 2,
  //     transform: 'scale(2.008) translate(0, 0.5) rotate(0)',
  //     borderRadius: [2],
  //   },
  // },
  // {
  //   id: 91,
  //   type: 'line-straight',
  //   parent_id: 87,
  //   children_id: 83,
  //   status: 'OFF_LINE',
  //   line_points: '0 -2, 0 4',
  //   arrow_transform: 'translate(0 4) rotate(-90)',
  //   no_circle: true,
  //   style: {
  //     top: 510,
  //     left: 762,
  //     width: 29,
  //     color: '#3474E4',
  //   },
  // },
  {
    id: 92,
    type: 'line-straight',
    parent_id: 84,
    children_id: 26,
    status: 'OFF_LINE',
    line_points: '0 0,12 0, 12 -28,68 -28',
    arrow_transform: 'translate(69 -28) rotate(180)',
    style: {
      top: 428,
      left: 1087,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 93,
    type: 'line-straight',
    parent_id: 83,
    children_id: 26,
    status: 'OFF_LINE',
    line_points: 'M 0 0, L 160 0, 160 -110, 165 -110 A 20 50 0 0 0 175 -110 L 189 -110',
    isArc: true, //是否显示为弧段
    //M 0 0 L 200 0  A 20 50 0 0 1 220 0 L 400 0  A 20 弧线x轴半径，50弧线Y轴半径,第三个参数是角度,第四个参数0是短边1是长边，第五个参数是否是顺时针0逆时针1顺时针
    //第六个参数终点X坐标 Y坐标  //控制弧线向上还是向下用顺时针参数控制
    arrow_transform: 'translate(189 -110) rotate(180)',
    style: {
      top: 650,
      left: 847,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 94,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 26,
    children_id: 33,
    line_points: '0 0,32 0',
    arrow_transform: 'translate(32 0) rotate(180)',
    style: {
      top: 85,
      left: 1273,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 95,
    type: 'line-straight',
    line_points: '0 0,32 0',
    parent_id: 26,
    children_id: 35,
    status: 'OFF_LINE',
    arrow_transform: 'translate(32 0) rotate(180)',
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 403,
      left: 1273,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 96,
    type: 'line-straight',
    line_points: '0 0,0 25',
    status: 'OFF_LINE',
    parent_id: 33,
    children_id: 34,
    arrow_transform: 'translate(0 -4) rotate(90)',
    line_start_arrow_transform: 'translate(0 25)  rotate(-90)',
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 169,
      left: 1741,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 97,
    parent_id: 104,
    children_id: 103,
    type: 'equipment',
    equipment_name: '高速数传基带',
    device_key: 'DDT',
    equipment_icon: 'normal',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '载波锁定',
        value: 2,
        key: 'status',
      },
      {
        label: '码元锁定',
        value: 1,
        key: 'status',
      },
      {
        label: '码速率',
        value: '450M',
      },
      {
        label: '解调模式',
        value: 'BPSK',
      },
      {
        label: 'Eb/N0',
        value: '30.1dB',
      },
      {
        label: 'AGC',
        value: '30.1dB',
      },
    ],
    equipment_style: {
      width: '48%',
    },
    style: {
      top: 512,
      left: 1338,
      width: 270,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 98,
    type: 'equipment',
    equipment_name: 'DTE',
    device_key: 'DTE',
    parent_id: [101, 102],
    children_id: 105,
    equipment_icon: 'dte',
    status: 'NORMAL',
    equipment_details: [
      {
        label: '设备情况',
        value: '正常',
      },
      {
        label: '控制方式',
        value: '本控',
      },
      {
        label: '工作方式',
        value: '待机',
      },
    ],
    style: {
      top: 221,
      left: 1675,
      width: 144,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 99,
    type: 'equipment',
    parent_id: 105,
    children_id: 107,
    equipment_name: '防火墙/交换机',
    equipment_icon: '',
    status: 'NORMAL',
    equipment_details: [],
    style: {
      top: 371,
      left: 1688,
      width: 118,
      height: 118,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 100,
    type: 'equipment',
    parent_id: [106, 103],
    children_id: null,
    equipment_name: '存储转发',
    equipment_icon: '',
    status: 'NORMAL',
    equipment_details: [],
    style: {
      top: 517,
      left: 1688,
      width: 118,
      height: 118,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 101,
    type: 'line-straight',
    parent_id: 34,
    children_id: 98,
    status: 'OFF_LINE',
    line_points: '0 0, 23 0,23 30,59 30',
    arrow_transform: 'translate(59 30) rotate(180)',
    style: {
      top: 223,
      left: 1558,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 102,
    type: 'line-straight',
    parent_id: 35,
    children_id: 98,
    status: 'OFF_LINE',
    line_points: '0 0, 23 0,23 -50,59 -50',
    arrow_transform: 'translate(59 -50) rotate(180)',
    style: {
      top: 407,
      left: 1558,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 103,
    parent_id: 97,
    children_id: 100,
    type: 'line-straight',
    status: 'OFF_LINE',
    line_points: '0 0, 40 0',
    arrow_transform: 'translate(40 0) rotate(180)',
    style: {
      top: 570,
      left: 1608,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 104,
    type: 'line-straight',
    parent_id: 51,
    children_id: 97,
    line_points: '0 0,32 0',
    arrow_transform: 'translate(32 0) rotate(180)',
    line_start: 'arrow',
    no_circle: true,
    status: 'OFF_LINE',
    style: {
      top: 570,
      left: 1273,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 105,
    type: 'line-straight',
    parent_id: 98,
    children_id: 99,
    line_points: '0 0,0 15',
    status: 'NORMAL',
    arrow_transform: 'translate(0 15) rotate(-90)',
    style: {
      top: 341,
      left: 1747,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 106,
    type: 'line-straight',
    parent_id: 100,
    children_id: 99,
    status: 'NORMAL',
    line_points: '0 0,0 -14',
    arrow_transform: 'translate(0 -14) rotate(90)',
    style: {
      top: 514,
      left: 1747,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 107,
    type: 'line-straight',
    parent_id: 99,
    children_id: null,
    line_points: '0 0,32 0',
    arrow_transform: 'translate(32 0) rotate(180)',
    line_start: 'arrow',
    no_circle: true,
    status: 'NORMAL',
    style: {
      top: 430,
      left: 1805,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 108,
    type: 'equipment',
    parent_id: null,
    children_id: [113, 111],
    equipment_name: 'X校零变频器',
    device_key: 'XZC',
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '频率',
        value: '8400.5000MHZ',
      },
      {
        label: '增益',
        value: '30db',
      },
    ],
    style: {
      top: 30,
      left: 20,
      width: 175,
      height: 102,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 109,
    type: 'equipment',
    parent_id: null,
    children_id: [112, 114],
    equipment_name: 'S校零变频器',
    device_key: 'SZC',
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    s_fed: true,
    equipment_details: [
      {
        label: '频率',
        value: '8400.5000MHZ',
      },
      {
        label: '增益',
        value: '30db',
      },
    ],
    style: {
      top: 450,
      left: 20,
      width: 175,
      height: 102,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 110,
    parent_id: null,
    children_id: [112, 111],
    type: 'img',
    status: 'OFF_LINE',
    url: require('../../assets/images/equipment-admin/tianxian.png'),
    style: {
      top: 170,
      left: 20,
      width: 177,
      height: 211,
      color: '#61666A',
    },
  },
  {
    id: 111,
    type: 'line-straight',
    parent_id: 108,
    children_id: 100,
    line_points: '0 0,0 30',
    status: 'OFF_LINE',
    arrow_transform: 'translate(0 30) rotate(-90)',
    line_start_arrow_transform: 'translate(0 0)  rotate(90)',
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 130,
      left: 107,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 112,
    type: 'line-straight',
    parent_id: 109,
    children_id: 110,
    line_points: '0 0,0 30',
    status: 'OFF_LINE',
    arrow_transform: 'translate(0 30) rotate(-90)',
    line_start_arrow_transform: 'translate(0 0)  rotate(90)',
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 380,
      left: 107,
      width: 29,
      color: '#3474E4',
    },
  },
  // {
  //   id: 113,
  //   type: 'line-straight',
  //   parent_id: 108,
  //   children_id: 1,
  //   status: 'OFF_LINE',
  //   line_points: '0 0,12 0',
  //   arrow_transform: 'translate(12 0) rotate(180)',
  //   // line_start: 'arrow',
  //   no_circle: true,
  //   style: {
  //     top: 80,
  //     left: 195,
  //     width: 29,
  //     color: '#3474E4',
  //   },
  // },
  // {
  //   id: 114,
  //   type: 'line-straight',
  //   status: 'OFF_LINE',
  //   parent_id: 109,
  //   children_id: 2,
  //   line_points: '0 0,12 0',
  //   arrow_transform: 'translate(12 0) rotate(180)',
  //   // line_start: 'arrow',
  //   no_circle: true,
  //   style: {
  //     top: 500,
  //     left: 195,
  //     width: 29,
  //     color: '#3474E4',
  //   },
  // },
  {
    id: 115,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    // line_start: 'arrow',
    no_arrow: true,
    no_circle: true,
    style: {
      top: 50,
      left: 367,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 116,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,12 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    // line_start: 'arrow',
    no_arrow: true,
    no_circle: true,
    style: {
      top: 380,
      left: 367,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 117,
    type: 'line-straight',
    parent_id: 29,
    status: 'OFF_LINE',
    children_id: 31,
    line_points: '0 0, 105 0, 105 30, 133 30',
    arrow_transform: 'translate(133 30) rotate(180)',
    style: {
      top: 120,
      left: 649,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 118,
    type: 'line-straight',
    parent_id: 29,
    status: 'OFF_LINE',
    children_id: 31,
    line_points: '0 0, 45 0, 45 -42',
    // arrow_transform: 'translate(133 30) rotate(180)',
    no_arrow: true,
    style: {
      top: 180,
      left: 649,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 119,
    type: 'equipment',
    equipment_name: 'S合成网络',
    device_key: 'S_CIN',
    parent_id: 91,
    children_id: 124,
    equipment_icon: 'comprise-network',
    status: 'OFF_LINE',
    s_fed: true,
    equipment_details: [
      {
        label: '频率',
        value: '12345.1234Hz',
      },
      {
        label: '旋向',
        value: '左旋',
      },
      {
        label: '增益',
        value: '00db',
      },
    ],
    style: {
      top: 408,
      left: 677,
      width: 170,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 10px',
      fontSize: '14px',
    },
  },
  {
    id: 120,
    type: 'equipment',
    parent_id: 86,
    children_id: 123,
    equipment_name: 'S下变频器1',
    device_key: 'SDC2',
    equipment_icon: 'transducer',
    status: 'OFF_LINE',
    s_fed: true,
    equipment_details: [
      {
        label: '衰减',
        value: '30db',
      },
      {
        label: '效率',
        value: '12345.1234Hz',
      },
    ],
    style: {
      top: 520,
      left: 918,
      width: 170,
      height: 119,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '10px',
      fontSize: '14px',
    },
  },
  {
    id: 121,
    type: 'line-straight',
    parent_id: 78,
    children_id: 87,
    status: 'OFF_LINE',
    line_points: '57 0,57 -43,170 -43,170 -25,185 -25',
    arrow_transform: 'translate(185 -25) rotate(180)',
    style: {
      top: 486,
      left: 541,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 122,
    type: 'line-straight',
    parent_id: 79,
    children_id: 87,
    status: 'OFF_LINE',
    line_points: '0 0, 0 20,14 20',
    // no_arrow: 1,
    arrow_transform: 'translate(14 20) rotate(180)',
    style: {
      top: 539,
      left: 650,
      width: 29,
      color: '#3474E4',
      // zIndex: 1,
    },
  },
  {
    id: 123,
    type: 'line-straight',
    parent_id: 84,
    children_id: 26,
    status: 'OFF_LINE',
    line_points: '0 0,30 0, 30 -85,68 -85',
    arrow_transform: 'translate(68 -85) rotate(180)',
    style: {
      top: 578,
      left: 1087,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 124,
    type: 'line-straight',
    parent_id: 84,
    children_id: 26,
    status: 'OFF_LINE',
    line_points: '0 0,140 0,140 -60, 188 -60',
    arrow_transform: 'translate(188 -60) rotate(180)',
    style: {
      top: 509,
      left: 848,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 125,
    type: 'equipment',
    equipment_name: '综合基带(测控)',
    device_key: 'BBE',
    parent_id: 96,
    children_id: 101,
    equipment_icon: 'acu',
    status: 'OFF_LINE',
    equipment_details: [
      {
        label: '工作方式',
        value: '待机',
      },
      {
        label: '天线位置',
        value: '123.123，123.123',
      },
      {
        label: '相位',
        value: '123，123',
      },
    ],
    style: {
      top: 175,
      left: 1338,
      width: 220,
      height: 124,
      color: '#61666A',
      boxShadow: '0px 0px 6px rgba(0,0,0,0.16)',
      background: '#F9FBFC',
      borderRadius: [4],
      padding: '5px 16px',
      fontSize: '14px',
    },
  },
  {
    id: 126,
    type: 'line-straight',
    line_points: '0 0,32 0',
    parent_id: 26,
    children_id: 35,
    status: 'OFF_LINE',
    arrow_transform: 'translate(32 0) rotate(180)',
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 235,
      left: 1273,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 127,
    type: 'line-straight',
    line_points: '0 0,35 0',
    parent_id: 26,
    children_id: 35,
    status: 'OFF_LINE',
    arrow_transform: 'translate(35 0) rotate(180)',
    line_start: 'arrow',
    no_circle: true,
    style: {
      top: 95,
      left: 1558,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 128,
    type: 'rect-mini',
    parent_id: null,
    status: 'OFF_LINE',
    children_id: 70,
    style: {
      top: 91,
      left: 696,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #C3C9D2',
      borderRadius: [2],
    },
  },
  {
    id: 129,
    type: 'rect-mini',
    parent_id: null,
    status: 'OFF_LINE',
    children_id: 70,
    style: {
      top: 217,
      left: 706,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #C3C9D2',
      borderRadius: [2],
    },
  },
  {
    id: 130,
    type: 'rect-mini',
    parent_id: null,
    status: 'OFF_LINE',
    children_id: 70,
    style: {
      top: 278,
      left: 569,
      width: 24,
      height: 10,
      background: 'rgba(255,255,255,0.39)',
      border: '1px solid #C3C9D2',
      borderRadius: [2],
    },
  },
  {
    id: 131,
    type: 'line-straight',
    parent_id: 29,
    status: 'OFF_LINE',
    children_id: 31,
    line_points: '0 0,88 0',
    // no_arrow: true,
    arrow_transform: 'translate(88 0) rotate(180)',
    style: {
      top: 95,
      left: 742,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 132,
    type: 'line-straight',
    parent_id: 29,
    status: 'OFF_LINE',
    children_id: 31,
    line_points: '0 0, 5 0',
    // arrow_transform: 'translate(133 30) rotate(180)',
    no_arrow: true,
    style: {
      top: 95,
      left: 720,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 133,
    type: 'line-straight',
    parent_id: 29,
    children_id: 44,
    status: 'OFF_LINE',
    line_points: '0 0,20 0,20 20',
    arrow_transform: 'translate(20 20) rotate(-90)',
    style: {
      top: 222,
      left: 756,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 134,
    type: 'line-straight',
    parent_id: 38,
    children_id: 41,
    status: 'OFF_LINE',
    line_points: '0 0, 10 0',
    arrow_transform: 'translate(51 28) rotate(-90)',
    no_arrow: true,
    active_color: '#C3C9D2',
    style: {
      top: 221,
      left: 730,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 135,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    line_points: '0 0,10 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    // line_start: 'arrow',
    animateStartRight: true,
    no_arrow: true,
    no_circle: true,
    style: {
      top: 50,
      left: 400,
      width: 29,
      color: '#3474E4',
    },
  },
  {
    id: 136,
    type: 'line-straight',
    parent_id: 25,
    children_id: 47,
    status: 'OFF_LINE',
    line_points: '0 0,10 0',
    no_arrow: 1,
    arrow_transform: 'translate(41 -8) rotate(90)',
    style: {
      top: 282,
      left: 592,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 137,
    type: 'line-straight',
    parent_id: 25,
    children_id: 47,
    status: 'OFF_LINE',
    line_points: '0 0,12 0,12 25,24 25',
    arrow_transform: 'translate(24 25) rotate(180)',
    style: {
      top: 282,
      left: 630,
      width: 29,
      color: '#C3C9D2',
    },
  },
  {
    id: 138,
    type: 'line-straight',
    status: 'OFF_LINE',
    parent_id: 15,
    children_id: 2,
    s_fed: true,
    line_points: '0 0,10 0',
    arrow_transform: 'translate(12 0) rotate(180)',
    // line_start: 'arrow',
    animateStartRight: true,
    no_arrow: true,
    no_circle: true,
    style: {
      top: 380,
      left: 400,
      width: 29,
      color: '#3474E4',
    },
  },
];
export const topologyData = {
  polarity_device: ['ACU', 'CPB'], //极化开关所属设备
  exclude_device: [], //不能点击的设备
  always_online: [22, 23, 24, 25, 29, 38, 63, 64, 65, 66, 78, 79, 80, 81, 98, 99, 100],
  matrix: {
    '70M': 26,
    '1.2G': 51,
  }, //中频矩阵
  element: topologyElement,
};
